### PR TITLE
HIP draft: Community Entry Gate

### PR DESCRIPTION
**Pull request by robputt**
Proposes a new HIP to resolve community tensions relating to clashes between experienced and inexperienced members.

Ed: rendered view https://github.com/helium/HIP/blob/ba59476d4e2e25dd44ff27b71b728ef1db46cd6a/0043-community-entry-gate.md

### CODE REVIEW

**Comment by shawaj** [comment]
as i said [here](https://github.com/helium/HIP/pull/290#issuecomment-953866941) on @ganey previous HIP draft #290 i do think we should include procedural and other stuff in HIPs that is non-blockchain related. As it is important to the community and network users in general

**Comment by jamiew** [comment]
`Meta` is definitely a valid category and process improvements are welcome. HIP7 and HIP19 are notable examples of this. While we've never seen proposals around Discord and how community tooling like that is managed, I am happy to merge this for discussion and see what everyone else thinks.

**Comment by jamiew** [comment]
@robputt I take issue with some of the hostile language towards new, less experienced users in this proposal, which starts with the very first sentence. I think discussions of Discord and community improvements like this are healthy, but I would like us to remain professional, constructive and inclusive in our language and tone.

Would you be willing to tone some of this down? I would be happy to provide specific notes if necessary.

**Comment by robputt** [comment]
> @robputt I take issue with some of the hostile language towards new, less experienced users in this proposal, which starts with the very first sentence. I think discussions of Discord and community improvements like this are healthy, but I would like us to remain professional, constructive and inclusive in our language and tone.
> 
> Would you be willing to tone some of this down? I would be happy to provide specific notes if necessary.

Good Morning @jamiew 

The language is deliberately designed to be hostile to add affect to the HIP and project an understanding of the current state of the community. Greta Thunberg didn't get on TV by asking someone to nicely care about the penguins. I feel the HIP is not just critical of new members but also the vultures which pray upon them. The main aim here is to shock and get this problem out in the open and seek resolution. Far bigger crimes happen in the Discord daily compared to the tone of my HIP.

Best Regards,

Rob

**Comment by pdogbc** [comment]
> @robputt I take issue with some of the hostile language towards new, less experienced users in this proposal, which starts with the very first sentence. I think discussions of Discord and community improvements like this are healthy, but I would like us to remain professional, constructive and inclusive in our language and tone.
> 
> Would you be willing to tone some of this down? I would be happy to provide specific notes if necessary.

Which words specifically are hostile to you? I see it important to have some attention grabbing features and don't see how some slightly edgy wording is hostile.

**Review by Dany8921 — APPROVED** [review]

**Comment by 23rdstudios** [comment]
As someone that is new to helium mining but is very tech savy and has been mining other currencies for a long time. The helium network, api is very off putting even with reading, watching video and everything that is suggested in the proposal. Discord is a shit show and is the tech version of fox news or facebook for many, Though the experienced users don't offer insight and while the best way to learn is from talking things out with people that have faced the same issues. Like why is my hotspot offline for two weeks for no good reason. Maybe just start a wikipedia page for Helium education and history. Because in my limited experience the community seems to have on comment to solve everything "Just wait, it will fix itself" the helium network in many ways seems like hitting the side of the tv back in the day or blowing in the Nintendo game to get it to work. While we are all busy, if you don't like what happening on discord maybe don't go on it or help those in need as an experienced community member should.

**Comment by jamiew** [comment]
In light of the author's desire to keep the strong language of the HIP and the lack of other changes in the last several months, I am closing this HIP as inactive. If it is still under consideration (and you're willing to tone things down) we are always happy to re-open and re-consider. Thank you!

**Pull request closed without merging**
