### PR TITLE
Added network badges to README

### PR DESCRIPTION
**Pull request by samgutentag**
Saw [this request](https://discord.com/channels/404106811252408320/404106811252408322/1228404310111424572) in Discord and change was pretty simple to make.

image

> [!IMPORTANT]  
> Someone please double check these! I pulled from heliumvote.com for some, others that have not yet been voted on or did not go to vote I took best judgements 

Network Badge colors extracted from the SVGs on HeliumVote.com as follows.

Network | Hex Code | Preview
---|---|---
HNT | #2755F8 | </img>
IOT | #26ED75 | </img>
MOBILE | #009EF8 | </img>

---

## Sample Preview of GitHub Rendering

|  ID | Title                                                    | Status                                                                                                        | Network                                                      |
| --: | :------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------- |
| 200 | [HNT Network Proposal](https://github.com/helium/HIP)    | [</img>](https://github.com/helium/HIP)          | </img>    |
| 201 | [IOT Network Proposal](https://github.com/helium/HIP)    | [</img>](https://github.com/helium/HIP) | </img>    |
| 202 | [MOBILE Network Proposal](https://github.com/helium/HIP) | [</img>](https://github.com/helium/HIP)       | </img> |

### CODE REVIEW

**Comment by waveform06** [comment]
That was quick - amazing, I was thinking though. What would the badges mean?
Voted with, or affects the network? Do some HIPs need more than one badge?
HIPs 4 & 8- & 52 voted with HNT but affects IOT
HIPs 7, 76 & 77 voted with HNT but affects all 3
HIP 12 voted with HNT but affects IOT and MOBILE

To help with knowing which HIPs defined each network going to be adding these to docs which could be a better lookup than badges
https://docs.google.com/document/d/1wR07EgMd5mZQ02GY750LQ6bIeZ_6-zyWNvvtS_obvRo/
https://docs.google.com/document/d/18BqeT0-SK83KvaBNdyUKHNr0A9ZgRlEC2YQCUVahfcA/

**Comment by samgutentag** [comment]
good question, spirit of the original request was "type or category of hip" which I read more as "which network this impacts". 

Pre-migration HIPs I think are fine to mark down as HNT, given thats all there was at the time, but maybe post migration HIPs (anythign after 70) we base it on the token used to vote?

**Comment by waveform06** [comment]
HIP 110 will be 3 votes, so it will get 3 badges

**Comment by samgutentag** [comment]
the benefit and curse of modular governance haha here is a sample of that that could lol like

|  ID | Title                                                    | Status                                                                                                        | Network                                                      |
| --: | :------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------- |
| 200 | [HNT Network Proposal](https://github.com/helium/HIP)    | [</img>](https://github.com/helium/HIP)          | </img>    |
| 201 | [IOT Network Proposal](https://github.com/helium/HIP)    | [</img>](https://github.com/helium/HIP) | </img>    |
| 202 | [MOBILE Network Proposal](https://github.com/helium/HIP) | [</img>](https://github.com/helium/HIP)       | </img> |
| 110 | [Multi Badge Test](https://github.com/helium/HIP) | [</img>](https://github.com/helium/HIP)       | </img> </img> </img>   |

**Comment by abhay** [comment]
I like the idea of this from a visualization perspective. It might need some work on mobile but fine with landing it after a rebase.

**Comment by samgutentag** [comment]
nice! should be all set, updated HIP 119 to include the </img> badge as well

**Comment by abhay** [comment]
did a quick reformat. probably needs a review of the tagging though. i think some of them are missing

**Comment by Ridvan8899** [comment]
.

**Review by devilish66694 — APPROVED** [review]

**Review by devilish66694 — APPROVED** [review]

**Comment by abhay** [comment]
need a rebase before considering a merge.

**Comment by samgutentag** [comment]
closing in favor of pr #1082

**Pull request closed without merging**
