### PR TITLE
Hip134 update 2

### PR DESCRIPTION
**Pull request by jhella**
Updates and clarifications based on the October 10th Mobile Working Group Meeting.

### CODE REVIEW

**Comment by abhay** [comment]
Is this ready to land, @jhella?

**Comment by jhella** [comment]
@abhay I need to confirm implementation details and coding commitments from madninja. I was planning to ping him in the hip channel on Monday during business hours. Thanks for checking.

**Comment by jhella** [comment]
@madninja I added some questions/comments in the HIP 134 discord channel.  Feel free to reply there at your convenience.

**Review by zer0tweets — COMMENTED** [review]
We should specify 25 unique locations during the trailing 7 days. Not just 25 connections ever, no?

**Comment by jhella** [comment]
@zer0tweets That's a good clarification.  The intent was trailing, not 25 connections ever.  Will update to be more clear once I've collected other comments.

**Comment by jhella** [comment]
@abhay @waveform06 Please change the HIP and channel name to: 

HIP 134: Reward MOBILE Carrier Offload Hotspots

I was informed by Madninja this program is technically no longer in beta so I'm updating the title as such.  With the title update and full approval of PR 1104 we're ready to go to vote as discussed in the MWG today.

**Pull request merged**
