### PR TITLE
0127-reverse-hip113

### PR DESCRIPTION
**Pull request by block070**
This proposal suggests reversing HIP 113. The primary objective of HIP 113 was aimed to reduce the coverage points for CBRS radios by 75%, adjusting the reward distribution to better balance the network's incentives. This change was intended to address the discrepancies in rewards between CBRS radios and Wi-Fi hotspots, ensuring a more equitable distribution based on the actual coverage provided by these devices. However, after its implementation, several unforeseen consequences and challenges have emerged. This proposal aims to outline the reasons for reversing HIP 113, addressing its negative impacts, and proposing a more balanced approach for the Helium community.

### CODE REVIEW

**Comment by waveform06** [comment]
@block070 You are missing some success criteria.
What can be measured or observed to show this HIP has succeeded in its Motivation.

**Comment by block070** [comment]
> @block070 You are missing some success criteria. What can be measured or observed to show this HIP has succeeded in its Motivation.

@waveform06 - I assume you are pointing to success criteria for HIP 113. Outside of the increase in sales of wifi units which could also be correlated to the increased ROI with the passing of HIP 113, do you have other success factors that you think I am missing? CBRS has a higher signal strength and a beta solution on the market that nobody but about 20 people have access to. If a mere sim card is all that is between all and the 20 beta, then we should all be treated the same. The criteria laid out in HIP 113 to my knowledge, does not reflect CBRS Beta versus Wifi. I guess I go back to problem we are trying to address which is higher signal. 

I would question why are we not chasing the gold instead of the silver - CBRS can transmit at up to 47 dBm (50 watts) EIRP for Category B devices, and up to 30 dBm (1 watt) EIRP for Category A devices. In contrast, Wi-Fi devices generally transmit at much lower power levels, around 20-30 dBm (0.1 to 1 watt) EIRP. This means CBRS can provide significantly greater coverage and penetration compared to Wi-Fi.

I am happy to look at both sides and see what we are missing here.

**Comment by waveform06** [comment]
Well, a success criteria is something you want to achieve that can be measured.
And the HIP should be motivated to achieve something.
So what can you measure from your motivations?

**Comment by block070** [comment]
> Well, a success criteria is something you want to achieve that can be measured. And the HIP should be motivated to achieve something. So what can you measure from your motivations?

@waveform06 - I think I see what you're after...let me know your thoughts please...the HIP would improve upon measurable metrics stated including: 

  a.	Returning to Levelized Incentives for Scope. The deployments of CBRS are much more elaborate than plugging in a wifi hotspot in the wall and into the back of a router. With CBRS, deployment carries a lot higher scope and requires ongoing maintenance. CPI approval further validates the work. The expense of the hardware and equipment to hang & mount further add to the scope & cost of work and why the playing field needs to be levelized by returning rewards to where they were prior to the passing of this HIP. It is also worth stating that there are less people willing to climb or work at higher heights and those who do, request a premium for their work because of the demand.
  b.	Increase in CBRS Deployments: We are losing CBRS installations with a net loss of over 50 installs week over week. Measuring the increase in CBRS deployments will help stabilize the network and provide more signal strength as compared to wifi.

2.	Community Feedback: A significant portion of the Helium community will be rewarded more fairly and equitable. 

3.	Economic Impact: The economic implications of reversing HIP 113 will shift to a more competitive amount. Loss of CBRS units on the network should slow and hopefully steadily increase. 

Appended: 
Pushing Beta Forward - It is time to push beta forward if there are no significant concerns. Putting those in a cbrs beta class ahead of the pack without further inclusion options is irresponsible.

**Comment by JayLilRoseCollection** [comment]
There's noway they slap a "experimental" on it. The fact that the CBRS radios even still for SALE. This HIP shows the technology already moving to the 6G baicells has already introduced that setup. The people's network where they're now catering to "businesses" not residential. They then went and opened the #beta beyond the initial 20 people who were benefiting from that HIP. Wonder if rawrmaan was in that group CBRS next to 

fiber has shown to be better than Wi-Fi alone.

**Comment by waveform06** [comment]
@block070 Success Criteria are measurable things

Ref 1.  The only bit in there that looks like a Success Criteria is "returning rewards to where they were prior to the passing of this HIP" and thats not going to be measurable due to the change in the number of CBRS/WiFi hotspots and the changes the other HIPS will be having.

Ref 2. Is measurable but is successful if 1 more CBRS deployment happens, between two unspecified time/dates.

Ref A. Community feedback is not a measurable thing. HIP 113 was voted in with community feedback!! Feedback on this HIP in discord is currently negative. And what is "significant", what is "more fairly", what is "Contribution? And it seems that HIP success can measured by how difficult something is to deploy and its signal strength.

Ref B. I dont even understand what that means. Loss of CBRS should slow.....but earlier you have success as increasing. What is the "more equitable plan to reward contributors"

**Comment by JayLilRoseCollection** [comment]
Ref. B: What is the "more equitable plan to reward contributors". It's about not rewarding a few but keeping it equitable across the board and the deployment of helium wifi shouldn't have effected negatively on the CBRS rewards. 

Ref 2: The Wifi is just as "experimental" as CBRS and there shouldn't have been a reduction approved with "community" inputs or otherwise, especially being comprised of whales, until such a time that the CBRS hand off data returned numbers for evaluation (after a full Beta was concluded across the entire spectrum not just a pull of "20" that isn't even an accurate sampling of all deployed CBRS) of best data. While I can understand from a business model that wants to grow the business community, they can't create that at the expense of the general non-business CBRS deployers. This clearly created an advantage for wifi business deployers to move units and that's that. 

Then the system is also "rigged" in a way that if you don't stake your coins you don't get vote power so there's possibly an even larger community presence that would have voted against HIP 113. This is also a measurable factor if presented to the community at large not requiring a staking against any future HIPs over a specific time and date period. But they already know this and won't be receptive to that option.

**Comment by block070** [comment]
@JayLilRoseCollection - Agreed on Ref B, Ref 2, and other statements you made above.

**Comment by abhay** [comment]
Throwing an idea out there, it might be good to frame this HIP with the reversal criteria defined in HIP 113.

**Comment by block070** [comment]
> Throwing an idea out there, it might be good to frame this HIP with the reversal criteria defined in HIP 113 (if the author believes we have reached those thresholds).

Story seems to be that Nova wants to prolong this as long as they possibly can and ask a page and half of questions when the matter is not as complicated as they make it out to be. With the new beta, I have heard and experienced for myself on an iPhone 14 successful cbrs handoffs and the passing of data. Nova continues to use excuses in the chat like we need to utilize newer technology so going along with some hip that says you shouldn't need support for 2 sims is completely controversial. 

**Quoting HIP 113 - This is what is says for partial reversal option:** 

Partial Reversal Option
While CBRS faces many technical and integration challenges, it’s important to acknowledge that a) poor handoff performance to/from macro networks and b) the 2nd SIM requirement are the main factors limiting the technology’s adoption, and that if both of these problems are solved, the utility of CBRS to the Network will drastically increase.

In the future, either a) the community's rough consensus as determined by the Helium Foundation or b) a formal request from the Mobile Working Group may compel the Helium Foundation launch a veMOBILE vote called “HIP 113 Partial Reversal” if all of the following conditions are met:

A Service Provider representing at least 25% of active Subscriber NFTs on the Network is able to develop a single SIM/eSIM solution that enables subscriber devices to handoff from a macro network to CBRS radios and vice versa

The SIM/eSIM is offered to all of the Service Provider’s US subscribers as part of its main Service offering

The user experience of handing off to/from CBRS is indistinguishable to that of normal macro tower handoffs

Any disagreements or ambiguity regarding the criteria above shall be resolved by the outcome of the vote.


CONTINUED Comment

The fact is that people with phones that are older just aren't going to work as good if at all. The people I have talked to with an IPhone 14 or 15 (latest tech that should be used from last 2 years) are able to a) successfully pass data and b) able to install the second sim. People who don't have updated technology meaning updated phones may not be able to adopt and pass data through CBRS. 

The user experience has been successful from the testing I have done. 

Nova collaborators need to be nova collaborators and stop focusing on making ignorant comments to questions and start helping to facilitate on the rollout of solutions. Cut the crap, get to work. According to the cbrs experimental chat, Binance has liquidated most or all of its holdings. Congratulations Nova, another sign of your lack of success in losing a stakeholder.

BuckGup — Yesterday at 5:06 PM
iPhone 15 or the pro? I’ve found the iPhone 15 pro has worked amazingly for all things helium

JayLilRoseCollection — Yesterday at 3:17 PM
Works great on the Samsung Note 20 Ultra too

Mr. Charlie - Amplify Solutions — Yesterday at 3:08 PM
So… wow… CBRS works seamlessly for my iPhone 15
Thank you, thank you, thank you

JayLilRoseCollection — Yesterday at 3:37 AM
💯 😂 What do you think their doing with the wifi it ain't for the crib it's for businesses. So now we're nit picking on what size business? We already understand Helium is trying to fill a niche 🤦🏿 🤷🏿

**Comment by amirhaleem** [comment]
> Story seems to be that Nova wants to prolong this as long as they possibly can and ask a page and half of questions when the matter is not as complicated as they make it out to be.

I’m not sure who you’re talking about here, but Nova isn’t involved in the HIP process in general or HIP113 at all.

**Comment by waveform06** [comment]
@block070 
I dont work for Nova, I dont even own or have an investment in any CBRS or Wi-Fi hotspots. So not affected by the outcome of this HIP at all.
I'm a HIP editor so trying to advise so you have a properly structured HIP.
That goes into detail where it should in the right sections. And removes superfluous content.
That way people can understand what they are voting on.

**Review by devilish66694 — APPROVED** [review]
#Verify

**Review by devilish66694 — APPROVED** [review]

**Comment by block070** [comment]
The CEO of Nova (capcom in discord chats) and Digerati |Friend Request=Scammer posted information that I would like to capture in this record (Yesterday as mentioned below is 6/20/2024 with timezone referenced CDT). The article referenced is from https://web.archive.org/web/20231211182115/https://support.hellohelium.com/en/articles/8032602-helium-cbrs-roaming-known-issues as it was deleted from the website.

capcom — Yesterday at 5:54 PM
not sure how many times i have to say we aren't really pursuing cbrs much right now. until the customer experience improves for subscribers, or carrier partners tell us they want to use it, there is no particular value in us spending time there
[5:55 PM]
the article linked is old and no longer relevant. it refers to an old configuration that did not work well and was phased out many months ago (edited)

@capcom
not sure how many times i have to say we aren't really pursuing cbrs much right now. until the customer experience improves for subscribers, or carrier partners tell us they want to use it, there is no particular value in us spending time there

Block70 — Yesterday at 6:06 PM
How do we know that freedomfi isn’t contributing or causing the negative experience?

@Block70
How do we know that freedomfi isn’t contributing or causing the negative experience?

Digerati |Friend Request=Scammer — Yesterday at 6:07 PM
Because it'd be in their financial best interest for deployers and subscribers to have as positive an experience as possible (edited)
[6:09 PM]
There's a reason that the ISPs branching off into the MVNO space like Comcast and Spectrum only use Wi-Fi, not CBRS (edited)
[6:10 PM]
We're really just waiting on Apple and Google to improve cross-network compatibility/handoffs in their respective mobile operating systems, there isn't really anything more that Nova/HM/FreedomFi or anyone can do until that happens (edited)

@Block70
How do we know that freedomfi isn’t contributing or causing the negative experience?

capcom — Yesterday at 6:12 PM
because the issues are: 1) phones are not very good at switching between two overlapping networks, specifically helium + TMO in our (helium mobiles) case. the idea of having two cellular networks sitting on top of each other is quite new, and phone support for it is limited at best. we have tried various workarounds and approaches, none of them are very good and have very poor user experience. there is a lot of detail here that I have posted over the months, and 2) carrier partners have so far not expressed much interest in using CBRS networks for their own traffic. this isn't unique to helium or nova, you also don't see cable companies making much use of their CBRS spectrum (they even paid for the spectrum and still dont use it) for exactly the same reason as point #1 - they are operating MVNO's that use an MNO network, and phones don't know how to switch between their own CRBS network and the MNO network cleanly

neither of these points has anything to do with how reliable the gateway or radio is. they could have 2000 nines of uptime and it would not change either point (edited)
[6:16 PM]
the beta sim program kind of works ok, but there are a lot of caveats...1) subscribers have to install a second sim, 2) they have to be in range of a CBRS network to activate that second sim, 3) they have to install a geofencing profile that is specific to their geography as iOS only allows you to include 1000 radios in the profile, 4) there needs to be a way to update the profile over time as radios get added or removed, so either a manual app prompt or some other mechanism that doesn't yet exist, and 5) in the case of android, you have to work through google to add and remove radios to their equivalent version of the geofencing profile without using geofencing, phones don't look for new networks very often. in the iPhone's case that is every 6 minutes. so you don't have very quick network switching. and the reverse case is true - you can wander away from the CBRS network but be stuck with no service for several minutes until the phone decides to scan for networks again. the geofence profile basically tells the phone where radios are, and to look for new networks more aggressively within those areas. but it has the issues described above that currently have no great workarounds
[6:18 PM]
the most optimal way to do it would be to have the CBRS radios connected to TMO's core (in the case of helium mobile specifically). that way the helium radios would be part of the TMO network in the same way as any other cell tower. but they are not interested in doing that today. maybe it would change in the future

capcom — Yesterday at 6:20 PM
that is the summary. TLDR - CBRS works fine, the "handoff issue" is specific to the helium mobile use case of having both TMO and Helium as providers. and so far no carrier partners have expressed any desire to use CBRS for offloading their subscribers

block70 thoughts: While still looking over things, this did provide a bit of a perspective from the CEO of Nova Labs on where we are today.

**Review by devilish66694 — APPROVED** [review]
0127-reverse-hip113

**Comment by madninja** [comment]
> 0127-reverse-Note

@devilish66694 note that you've been blocked from commenting/approving in this GH team. Blank approving PRs without any discussion is usually associated with credability farming, and not helpful to the community

**Comment by mrfizzy99** [comment]
@block070   
Are you ready to edit the HIP to be conformed to the standards of other HIPs?  Otherwise, best to pull a bender here. 

image

**Comment by devilish66694** [comment]
Verified

**Comment by devilish66694** [comment]
#966

**Review by devilish66694 — APPROVED** [review]
block070:0127-reverse-hip113

**Review by devilish66694 — APPROVED** [review]

**Review by devilish66694 — APPROVED** [review]

**Review by devilish66694 — APPROVED** [review]

**Review by devilish66694 — APPROVED** [review]

**Comment by waveform06** [comment]
@block070 Will this PR be updated with the requested content or is it time to close it?

**Comment by abhay** [comment]
marking this HIP for archive.

**Pull request closed without merging**
