### PR TITLE
Create XXXX-obfuscating-live-voting-results.md

### PR DESCRIPTION
**Pull request by heatedlime**
This HIP proposes removing live voting results on HIPs to encourage voter turnout.

### CODE REVIEW

**Comment by abhay** [comment]
I don't think this needs a HIP. I think it's just a feature request for modular governance, our implementation of it, etc.

I think to start, we can just do it twitter/X style. i.e. one can't see the results until their logged in wallet votes (a UX feature we could add to [helium-vote](https://github.com/helium/helium-vote)) or after the vote deadline passes.

Blind voting is probably something we'd look into in the future and I'd love to work with someone like [Light Protocol](https://docs.lightprotocol.com/) to make this happen.

**Comment by heatedlime** [comment]
Sweet. Is it possible to not display the % and vote count once someone votes? Like it can tell them if the HIP is passing or not, but not how many more votes it needs to pass. This prevents someone from trying to buy votes.

**Comment by abhay** [comment]
> Sweet. Is it possible to not display the % and vote count once someone votes? Like it can tell them if the HIP is passing or not, but not how many more votes it needs to pass. This prevents someone from trying to buy votes.

Yep want to file an issue on the other repo so we can discuss there?

**Comment by heatedlime** [comment]
Closing this as created issue #816 in it's place https://github.com/helium/HIP/issues/816

**Comment by heatedlime** [comment]
Closing this as created issue https://github.com/helium/HIP/issues/816 in it's place https://github.com/helium/HIP/issues/816

**Pull request closed without merging**
