### PR TITLE
HIPxx: Regional reward adjustments

### PR DESCRIPTION
**Pull request by mj0lken**
Regional reward adjustments.
This proposal suggests the addition of a regional reward scaling chain variables to deal with different regional output regulation for the LoRa protocol in order to create an equal deployment incentive over the world.

_Ed – rendered view:_ https://github.com/mj0lken/HIP/blob/HIP-32/0032-regional-reward-adjustments.md

### CODE REVIEW

**Comment by jamiew** [comment]
Thank you for the proposal! I'm putting as "HIPxx" while we review before fully numbering and merging. I'm out today but will review ASAP

**Comment by jamiew** [comment]
@mj0lken I'm planning to merge momentarily, any interest in presenting this and fielding any questions for 5-15 mins on the community call tomorrow? More info: https://dewi.org/community-call or feel free to hit me up on Discord `jamiedubs#1105`

**Comment by jamiew** [comment]
Tarcking issue https://github.com/helium/HIP/issues/222

**Comment by capjbadger007** [comment]
Voting to close this and archiving the related HIP discord channel. @jamiew

**Pull request merged**
