### PR TITLE
T.M.G INDUSTRIES - HIP19 third party manufacturer application

### PR DESCRIPTION
**Pull request by TyeG1250**

### CODE REVIEW

**Comment by Sophi** [comment]
Rendered view: https://github.com/helium/HIP/blob/ec500a814e1381422c72ee9bbc97a7a49ca6c610/0019-third-party-manufacturers/T.M.G%20INDUSTRIES%20.md

**Comment by Sophi** [comment]
Thanks for your proposal! We'll be in touch.

**Comment by Sophi** [comment]
Hello, please provide a contact email. Thanks!

**Comment by TyeG1250** [comment]
Hi my contact email is tyrellgerald@gmail.com

**Comment by TyeG1250** [comment]
Hi Sophie 

Just wanted to give you a update we are currently in the process of getting the required documents for our certification and should hopefully have it by next week.

**Review by TyeG1250 — COMMENTED** [review]
This is the only area I can make any changes there is no option for me to add anything in the doc that was sent to me I could send the answered questions in a separate document if needed ?

**Pull request merged**
