### PR TITLE
HIP draft – Record all potential beacon witnesses

### PR DESCRIPTION
**Pull request by captainhindsite**
Please be gentle with me - this is my first foray into Github as well as HIP submission

### CODE REVIEW

**Comment by jamiew** [comment]
Hello and welcome @captainhindsite! 

rendered view:
https://github.com/helium/HIP/blob/d388b235a066360fe19a074730ac898cb53a3948/0049-display-all-potential-beacon-witnesses.md

will review & get back w/ any notes, or else number and merge for discussion + discord channel + etc

**Comment by captainhindsite** [comment]
Many thanks 👍

**Comment by jamiew** [comment]
@captainhindsite would you be interested in presenting this HIP at the community call today? noon ET https://dewi.org/community-call

I'll be reviewinga and likely merging this shorty as well, please excuse the holiday delay

**Comment by captainhindsite** [comment]
Sorry, I can't.

Important family business.

**Comment by ganey** [comment]
I like this proposal, I live in a rather hilly area and it's quite tricky to figure out what I can reach (especially without discovery mode), have to make a physical position change of my hotspots on the roof, then wait several weeks to see if there's any differences in witnesses

**Comment by captainhindsite** [comment]
Someone seems to have been able to comment on my HIP proposal, which led me
to check it out, and I see that a DRAFT tag has been added.

Can I ask please, what happens next?

**Comment by jamiew** [comment]
This HIP draft has been numbered and merged for discussion as HIP 50. https://github.com/helium/HIP/issues/331 

Please direct future questions & comments to the new tracking issue: #331

If you are one of the named authors, please include `#331` in future pull requests to have them automatically merged.

**Pull request merged**
