### PR TITLE
Clarifications to example table; doc with info about reward adjustment for Hotspots based on Mappers Input

### PR DESCRIPTION
**Pull request by meowshka**

### CODE REVIEW

**Comment by waveform06** [comment]
Actually, tokens emitted every 24 hours are 60B/365 not 5B/30
So 164,383,561 not 166,666,667 
And 32,876,712 not 33,333,333
Rewrad Points Earned by All Mappers <<< spelling mistake = Rewards
Im not sure on values MOBILE distribution calcs for the following:
MOBILE Earned per Discovery Mapper  
MOBILE Earned per Verification Mapper

**Comment by vincenzospaghetti** [comment]
@meowshka, do you see the comments above? Do you need to make any corrections because of that comment?

**Comment by vincenzospaghetti** [comment]
@meowshka can you review the comments on this before I merge?

**Comment by meowshka** [comment]
@vincenzospaghetti all changes look good and file is now accessible to everyone with the link.

**Pull request merged**
