### PR TITLE
HIP draft - LoRaWAN Committee Terms of Reference

### PR DESCRIPTION
**Pull request by vudutech**
# LoRaWAN Committee

- Author(s): [@leogaggl](https://github.com/leogaggl), [@tonysmith55](https://github.com/tonysmith55), [@buzzware](https://github.com/buzzware), [@jamesmeikle](https://github.com/jamesmeikle)
- Start Date: 2022-03-09
- Category: governance
- Original HIP PR: 
- Tracking Issue: 

# Summary
[summary]: #summary

The proposed change of frequency plan for Australia highlighted some major deficiencies on how the DEWI LoRaWAN committee is currently selected, operated and how the process can be improved for all impacted by the committee decisions.

This HIP suggests improvements in the following areas:
1. Selection of members and defining their roles
2. Declaration of conflict of interest
3. Governance procedures, such as reporting
4. Creation of sub groups to perform specific tasks or assignments to assist the committee decisions
5. Ethics guidelines
6. Process of including the affected regions in the decision-making process
7. Failures and consequences.

# Motivation
[motivation]: #motivation

Currently there are no publicly available Terms of Reference (TOR) for the DEWI LoRaWAN committee. This can place burden on the committee and the community creating an absence of clarity for both that has led to undesirable results.

Given the accelerated growth of the community, the number of diverse groups (such as makers, operators, and consumers) the number of diverse cultures (worldwide) that are asked to contribute time, financials (blood, sweat and tears) either directly or indirectly we believe it is now time to enact a governance framework that values all contributors to the community and continues to strengthen the resilience of it as it grows. 

This proposed change should be seen as a positive for the existing committee, as due to their effort thus far the community has grown to the size and complexity that requires more formal governance.

# Stakeholders
[stakeholders]: #stakeholders

There are two (2) stakeholder groups with this HIP:
 - DEWI LoRaWAN Committee
    - A clear governance structure will support the DEWI LoRaWAN committee to ensure strong, objective, sustainable and inclusive growth, without bias and conflict.
 - Wider Helium Ecosystem
    - Without a clear articulated governance structure decisions made will inadvertedly create unintended consequences. Such decisions, without adequate consultation, have the potential to create critical user issues and harm growth, which is the reason why selection and governance of this committee are so crucial.

We have started reaching out to people
 - Github repository feedback
 - Helium Community HIP Discord channel
 - Other relevant Helium Community Discord channels.

# Detailed Explanation
[detailed-explanation]: #detailed-explanation

The improvements are to be achieved by the development of a publically accessible Terms of Reference (TOR) that establishes the governance of the comittee, the following details provide a minimine guidence for what must be part of the TOR. 

## Guiding principles of the committee
The committee has a responsibility to:
 - operate in a transparent, timely and accountable manner at all times
 - communicate clearly and regularly with stakeholders and the DEWI as appropriate
 - adopt existing LoRa Alliance standards where applicable
 - act in conformance with the relevant regulatory bodies in each region
 - report to wider Helium Community via publicly accessible meeting minutes and / or communiques on meeting outcomes
 - endeavour to reach consensus within the committee, taking into account the views of all members.

The committee’s recommendations must:
 - not be inconsistent with LoRa Alliance standards and directives by regional regulators
 - be based on the best available scientific information, evidence based policy and encourage best practice in the Helium ecosystem
 - balance the technical implications and impacts of changes with the practicalities of operators, makers and consumers in the wider Helium ecosystem
 - be clear, logical and verifiable
 - demonstrate that the views of affected stakeholder groups have been considered
 - aim to reduce unnecessary, ineffective or duplicative regulation.

## Membership
Committee membership is critical to the transparency and capability of the committee for effective and independent in decision making.

The committee must consist of at least:
 - an independent chair (not connected to either DEWI or Helium Inc)
 - three LoRaWAN and/or RF engineering experts, to ensure appropriate technical expertise is maintained
 - one person with a practical understanding of the operational, technical and logistical facets
 - one standards development/regulation specialist.

A quorum must be established to proceed with the committee meeting.

 The committee should engage other external experts and participants invited by the chair as required and determined by the agenda.
 The committee has the opportunity to establish sub groups (may be topic or region specific) to provide advice the committee.

## Eligibility requirements and declarations of personal interests (conflicts of interest)
Each member is required to make a declaration confirming they met the eligibility requirements upon their appointment to the committee. Members must continue to comply with eligibility requirements.

During the operation of the committee, members are to declare to the chair all known actual or potential conflicts of interest as soon as they become aware of the conflict. Each meeting should contain a standard agenda item to allow for actual and perceived acknowledgement.

The initial declaration of eligibility made to the DEWI prior to joining the committee and subsequent statements of personal interest will be deemed to be a ‘standing statement’ for all meetings of the committee.

At each meeting, members are to advise of any new actual or potential conflicts of interest arising in respect of issues on the meeting agenda. These should be recorded in the minutes of the meeting, along with the course of action taken in relation to managing the conflict of interest. Where a conflict of interest is declared by a member on a particular agenda item, the chair is to consider the nature and extent of the conflict and adopt one of
the following courses of action:
 - allow the member to participate in discussion and in decision-making on the matter
 - allow the member to be involved in discussions on the matter but not be involved in making a decision in relation to the matter
 - exclude the member from participation in any discussion or decision-making on the matter
 - direct the member to leave the meeting during deliberation on the matter.

The use of external experts is also subject to conflict of interest considerations. Each potential external expert must declare any potential conflict of interest or any possible perception of bias that could prevent him or her from participating in the review of a particular issue/standard. If this declaration raises concerns about whether the external expert should participate in the review, the chair may nominate an alternative expert.

### Committee roles and responsibilities
The committee structure has been designed to balance the skills, interests and expertise of its members so that the group may offer sound advice to DEWI.

Role of individual members:
 - participate in meetings, engage in quality debate to give professional, independent and advice to the Chair 
 - Represent the consensus view of the community
 -	Understand the strategic impacts and outcomes of initiatives being considered
 - remaining fundamentally committed to the improvement of the Helium ecosystem
 - operating in a transparent, timely and accountable manner
 - ensuring all technical issues, new research and scientific knowledge submitted by stakeholders relating to technical matters have been properly considered by the committee and independent expert advice sought as necessary
 - contributing to the development of clear timelines and work plans for the committee
 - ensuring all interested stakeholders have the opportunity to provide review input
 - clearly analysing the benefits and costs of the proposed options for affected stakeholders in a balanced and objective manner.

Role of the independent chair:
 - chair meetings, including:
   - advising the committee about meeting protocols
   - Ensure actions from each meeting are discussed and managed to their conclusion
   - reminding committee members that they are bound by confidentiality provisions
   - managing declarations of conflict of interest
   - facilitate constructive processes that allow for continuous improvement DEWI and the Helium ecosystem overall
   - ensure work of the committee is conducted efficiently and that recommendations are presented to DEWI within agreed timelines
   - ensure committee members act in accordance with the guiding principles of the terms of reference in all aspects of operations
 - ensure the committee undertakes appropriate record keeping of decisions and actions
 - provide final approval of committee meeting papers and recommendations
 - provide progress updates and reporting to DEWI.
 - report to wider Helium community via meeting minutes and / or communiques on meeting outcomes

## Reporting arrangements
The committee, through the chair, will report to DEWI. In addition to their final recommendations the committee will provide a report that outlines their consultation process, issues raised by stakeholders and their deliberations in reaching their recommendations to DEWI.

The information shall be published on DEWI's website or Github repository. This information published will include information outlining the issues for consideration, the consultation timelines and updates on progress of the review. Submissions (unless clearly marked ‘IN CONFIDENCE’) and draft and final recommendations
will also be published on these pages.

# Drawbacks
[drawbacks]: #drawbacks

None.

The Helium ecosystem needs a governance framework to meet the fast growth that has occurred and allow continued positive growth for the community.

# Rationale and Alternatives
[alternatives]: #rationale-and-alternatives

- Why is this design the best in the space of possible designs?

No other proposals are currently available. Widest possible community feedback will be sought to consider in this proposal.

Best practice governance provides strong platform for growth, sustainability and resilience.

- What is the impact of not doing this?

Poor decision making and unnecessary disruption of the ecosystem due to such decisions. Regional disruptions and potential disconnect. Reduction of confidence in the Helium network.  If so by whom? Likely loss or reduction of network growth and adoption for all stakeholders.

# Unresolved Questions
[unresolved]: #unresolved-questions

- How does this governance proposal for the LoRaWAN committee fit in with an overall DEWI governance structure? 

- Do any decisions made by the LoRaWAN committee prior to the approval of this HIP need to be reviewed? Details of existing documentation has been sought?

- Does cyber security have enough representation within the committees?

What related issues do you consider out of scope for this HIP that could be addressed in the future independently of the solution that comes out of this HIP?

-Issue escalation procedure with Alliance
-Positive mental health of members (including reduction of burnout)
-Risk management.

-[TODO] add some more. 

# Deployment Impact
[deployment-impact]: #deployment-impact

There is no deployment impact. This HIP purely describes proper governance and procedures in the decision making process.

It will create a proper governance structure ensuring that decisions are made with proper consideration of all stakeholders and ensures that conflicts of interest have to be declared.

Documentation on this process should be made available via Helium Docs.

There are no backwards compatibility issues. The only potential issue is how to deal with decisions made prior to this change in governance.

# Success Metrics
[success-metrics]: #success-metrics

What metrics can be used to measure the success of this design?

- Faith of current Helium investors in regions
- Engagement by community in future decisions
- Alignment to best practice and possibility to lead by example
- Greater network uptake and usage aligned to improved committee process and outcomes.

### CODE REVIEW

**Comment by jaytheblader** [comment]
Nice work, I believe implementation of this proposal will go a long way to strengthen the process within the Helium LoRaWan committee.

**Comment by ajcrom** [comment]
Great document and on behalf of the wider Helium community , thanks for the work to put this together . 

HIP45 certainly exposed some gaps - but these are the necessary learnings and the evolution of a growing , inclusive , transparent , global ecosystem . 

Definitely a step in the right direction .

**Comment by buzzware** [comment]
Good work, it looks pretty thorough but it would be good to get feedback from people who do this kind of thing (not me).
One thing I suggest considering is representation from Europe and Asia Pacific regions, and representation of the Helium community ie those who have a significant following and respect from the Helium community via social media, blogs, podcasts etc.

**Comment by jamesmeikle** [comment]
Referencing a summary of why do we need this post: https://github.com/dewi-alliance/hplans/pull/28#issuecomment-1072949457

Thanks those that have provided feedback , read, commented here on and on other communities.

Any community that is this complex with so many moving parts needs the use of a documented TOR(s) and associated governance to survive a lengthy amount of time these days. There is likely some governance occurring but it is undocumented and thus not transparent to the community ,leading to some rather undesirable conversations. Good to hear the focus is being put on governance and also of the interest by a Helium representative to look at this HIP.

**Comment by ehrisbok** [comment]
This proposal is sorely needed. No governance & TOR leaves Helium open to to either poor decisions or accusations of conflicts of interest (real or imagined). Glad someone has put forth a well thought out document that promotes open & transparent governance. Which is critical for the Helium community

**Comment by Australian-Hnt-collectors** [comment]
Great work to those involved it is well due that governance is sorted out for any discussion

**Comment by shawaj** [comment]
Great work.

I think having the stakeholders clearly defined and clearly declaring their interests and motivations is very important.

There is no fundamental reason for commercial applications and considerations to be taken into account with these matters but they need to be clearly defined and any potential conflict of interest readily identified.

By no means do I want to jump on the conspiracy theory bandwagon but like all things the optics are the important thing with that. If someone appears to have a conflict of interest people will always assume, rightly or wrongly, that they are biased

**Comment by shawaj** [comment]
@vudutech one thing I'd like to see here though, representation from manufacturers.

They are important stakeholders in the ecosystem and are often not thought about.

In a wider way, I'm thinking perhaps a "manufacturers association" or something similar makes sense. Similar to how Formula 1 have a constructors and drivers association (just catching up on the qualifying hence my thought!)

**Comment by leogaggl** [comment]
Thanks for the input @shawaj - greatly appreciated!

> ...representation from manufacturers.
> 
> They are important stakeholders in the ecosystem and are often not thought about.

This did come up in our discussions when starting this HIP! @tonysmith55 in particular did bring up the way standards bodies are often governed with formal input from all stakeholder groups.

We tried initially to keep it simple and broad (as there was some concern from our community call about too many regulations "hindering fast innovation"):

_**"demonstrate that the views of affected stakeholder groups have been considered"**_

But I do agree with you that considering all stakeholder groups and allowing input is very important. A lot of this can also be avoided by transparency and good communication. 

> 
> In a wider way, I'm thinking perhaps a "manufacturers association" or something similar makes sense. Similar to how Formula 1 have a constructors and drivers association (just catching up on the qualifying hence my thought!)

I do think this is a good idea. However, it is probably outside of the scope of this HIP. It would make the inclusion process easier if there is a clear stakeholder group defined.

Would you be interested in helping us create a listing of stakeholder groups that should be considered? You mention manufacturers. Gateway manufacturers? Device manufacturers? Software vendors?

If you have any suggestions in terms of wording please do submit an issue or a PR on the repo https://github.com/leogaggl/HIP/blob/main/00XX-lorawan-committee.md

[On a more humorous note: I doubt Lewis Hamilton would argue that F1 should be taken as a model of transparency and great decisions ;-)]

**Comment by fahimshariff** [comment]
Great work we really need better governance and transparency .

**Comment by jaytheblader** [comment]
Thanks @shawaj for your input and support around this HIP, I believe it will if implemented form the basis to similar HIPs that help to address governance issues Helium / DeWi has in some other areas. You are absolutely correct in my opinion that a representative of the gateway manufacturers be considered as a committee position as long as any conflict of interest that could arise on occasion follows due process to allow the committee to be unbiased.

**Comment by Buckshot22** [comment]
Fantastic work guys, if there is anything I can do to help, please let me know. What has been presented so far is very comprehensive and should be a significant improvement to the current process.

**Comment by jamiew** [comment]
Hi @vudutech  @leogaggl, @tonysmith55, @buzzware, @jamesmeikle – would y'all be able to write this as an actual HIP file that can be merged into the repo, per convention? 

I've also written a rough guide to doing this using the github.com web interface: https://jamiedubs.com/blog/how-to-submit-helium-manufacturer-application/

**Comment by leogaggl** [comment]
Hi @jamiew,

Do you mean this file: https://github.com/leogaggl/HIP/blob/main/00XX-lorawan-committee.md? 

It was forked from HIP repo and based on the template.

Cheers,
Leo

**Comment by jamiew** [comment]
@leogaggl yes, thank you, I was thrown off the scent by having the full post in the PR body too (which is also convenient). Un-stale'ing and will review tomorrow for merger. Please forgive the delay!

**Comment by leogaggl** [comment]
I would be ready from our perspective to fix the issues around the Committee. So you can definitely take it out of the draft.

It really depends on how @Scottsigel and @edakturk14 want to take this forward. To me, it would make more sense as part of a wider governance HIP which also contains the fixes that @Scottsigel and the Australian community flagged as necessary on HIP-45 during the Town Hall session.

**Comment by vincenzospaghetti** [comment]
Following up to @leogaggl 's last comment. The Foundation, including myself, will be proposing a larger governance structure and processes. All of this will be taken into consideration and we'll engage the community shortly on our proposal.

**Comment by leogaggl** [comment]
This particular piece of work was related to HIP-45 which was quietly dropped by the foundation with little fanfare it seems.

I would agree that this can probably be closed and seen as another perfect example of a governance failure. I am happy to see some work done by yourself and @vincenzospaghetti - but unless the Helium Foundation Board steps up and treats this seriously I am afraid it seems little and very late.

**Comment by jamiew** [comment]
@leogaggl was the outcome from this and HIP45 something you don’t agree with, or is it just the process? 

I think everyone would welcome community participation from you and others in organizing committees like what you had proposed here, and would consider the outputs seriously

**Comment by leogaggl** [comment]
> @leogaggl was the outcome from this and HIP45 something you don’t agree with, or is it about the process of getting there?

Hey @jamiew - I was referring to the process in this context here. We had a whole process leading to a town hall meeting where Scott promised that the governance process will be addressed and no decision will be made without the affected community.

Instead there radio silence for over six months, the whole process discarded rather than fixed and then there was some "announcement" blaming the LoRa Alliance (which has actually stated previously that it does not take a position in those matters - as it is determined by the local authorities and the choice is up to the operator). 

You might as well not bother with governance and just let Nova Labs do what they like to do. And don't pretend the Helium Foundation is actually in charge.

**Pull request closed without merging**
