### PR TITLE
Create 0000-split-claimed-rewards-between-multiple-wallets.md

### PR DESCRIPTION
**Pull request by cipherkilledit**
This Helium Improvement Proposal introduces the concept of splitting claimed rewards between multiple wallets / parties.

### CODE REVIEW

**Comment by waveform06** [comment]
AFIK this is already on the feature Roadmap for the Helium Wallet. Recently Introduced was the ability to assign 100% of the rewards from a hotspot to a different wallet which was the first step in allowing splits of rewards.

As for the Nova Builder App being able to do this... The could just be a feature request to their app team.

**Comment by abhay** [comment]
I don't think it makes sense for the Helium protocol itself to support splits but as @waveform06 mentioned, assigning rewards to a different account and that account managing splits is probably the way to go. On Solana, another protocol team could offer this as a service with a smart account / PDA wallet.

**Comment by cipherkilledit** [comment]
To reach mass adoption, Helium needs to focus more on the user experience. 

What do you think is a better **user experience** for the average person trying to expand the Helium network?

1. Configuring a split on a per-hotspot basis within one of the existing apps
2. Downloading and configuring yet another app on top of all the apps they already need; Helium Builder, Helium Mobile, Helium Wallet, and a third party wallet to send gas to yourself.

**Comment by cipherkilledit** [comment]
Screenshot below; all the major NFT marketplaces support splits today. Why don't we enable Helium to support this too? 
image

**Comment by abhay** [comment]
Adding the computational complexity (how many splits, what are the different kinds of splits, are they percentages or flat amounts, etc.) and the potential liability to the protocol itself (what if there's a dispute on the split amount, who is the multisig that agrees on changes to the split, etc) seems out of scope of the Helium protocol itself.

There's a lot of prior art here [HIP-24](https://github.com/helium/HIP/blob/main/0024-reward-splitting.md) but ultimately we decided back then it doesn't make sense to implement this in the core protocol. The feature of a separate rewardable address was something added since moving to Solana since we could allow other developers to compose on top of Helium. This is a decent primitive for folks to build upon. I know the SolSplits team and the Relay team are both thinking about this.

**Comment by elijahlomaka** [comment]
@cipherkilledit @waveform06 we're working on re-enabling Payments in [Relay app](https://app.relaywireless.com/) in October and finalizing splits in Q4. With Relay Payments you'll be able to achieve same results as with splits by setting up commissions for your hosts. Payments are essentially MVP for Splits. Once Payments are live on Relay, we're planning to concentrate on finishing up smart contract for Helium Splits. Happy to jump on a call and discuss further if you have any questions. FYI Relay app is already available in public beta, you can go and give it a spin.

**Comment by cipherkilledit** [comment]
Thanks @elijahlomaka. The goal here is not to need ANOTHER app. Helium Builders already need 3 - 4 apps as it is. Are you saying Helium Splits will be built into one of the existing Helium apps? Is there already a HIP for that or can we use this one?

**Comment by elijahlomaka** [comment]
@cipherkilledit that's one of the paths we're considering! To make it happen, we would need community support in testing app.relaywireless.com and helping us by sharing feedback on our payments flows. This will ensure we have most tested splits and will be able to successfully integrate with Helium apps. DMed you on telegram to discuss further!

**Comment by abhay** [comment]
Going to close this as not intending to implement at the protocol layer. Open to open source contributions to the mobile app or other solutions like Relay or SolSplits to implement.

**Comment by cipherkilledit** [comment]
Thanks for the update. Who do I need to contact to add this functionality to the mobile app? It's sad to see all the NFT marketplaces support this but not a mature project like Helium.

Stay smart,
Team Cipher
http://CipherMusic.com
Https://cipher.fanlink.to/music
Https://cipher.fanlink.to/social
________________________________

**Pull request closed without merging**
