### PR TITLE
Proposed changes to HIP16 "random-consensus-group-election.md"

### PR DESCRIPTION
**Pull request by tjain-mcc**
Rendered view of updated version: https://github.com/helium/HIP/blob/af60c836913cba2fc56ee4e1202921dcd5c1174f/0016-random-consensus-group-election.md

Diff: https://github.com/helium/HIP/pull/56/files

### CODE REVIEW

**Comment by jamiew** [comment]
Tagging in @PaulVMo as original author -- feel free to comment on these changes and bless or reject a merge

**Comment by evanmcc** [comment]
My vote would be to table this until we (Helium) can put together a comprehensive proposal that involves staking.  I think that adding staking to score removal will needlessly delay score removal as we work out the political aspects of staking and the further evolution of the consensus group.

**Comment by PaulVMo** [comment]
I tend to agree with the idea of keeping staking as a separate though equally important HIP. There is no reason that can't be a HIP right now as well. How can we get broader input on whether or not to do an interim step of removing score?

**Comment by jamiew** [comment]
@PaulVMo @tjain-mcc I'm understanding that this means this specific patch is rejected, and it's suggested to move staking-related concepts to their own HIP. 

Please re-open if I got that wrong!

**Pull request closed without merging**
