### PR TITLE
IOTCOMM -  HIP19 third party manufacturer application manufacturer 

### PR DESCRIPTION
**Pull request by huangxian33**
IOTCOMM,Application to become an approved third party manufacturer.

Ed – rendered view: https://github.com/huangxian33/HIP/blob/master/0019-third-party-manufacturers/iotcomm.md

### CODE REVIEW

**Comment by jamiew** [comment]
Thanks for your submission. Someone from the manufacturing review committee will be in touch

**Comment by Sophi** [comment]
Hello! The contact email address you shared came back, can you please provide another one?

**Comment by huangxian33** [comment]
> 你好！您分享的联系电子邮件地址回来了，您能否提供另一个？

I'm very sorry, email error. Revised.
xian. huang@iotcomm.com

**Comment by huangxian33** [comment]
Hello. This is my email. I'm very sorry.

Thanks and best regards,

黄贤 / HUANG XIAN
Product Manager
XIAMEN IOTCOMM TECHNOLOGY CO.,LTD. 
Tel: 18906047861
Mail: ***@***.*** 
Wechat:huangxian33
Website: www.iotcomm.com.cn 
Address: No. 2002, Tongjizhong Road, Tong'an District, Xiamen, China.

 
From: Sophi Kravitz
Date: 2021-06-11 05:42
To: helium/HIP
CC: huangxian33; Author
Subject: Re: [helium/HIP] IOTCOMM - HIP19 third party manufacturer application manufacturer (#203)
Hello! The contact email address you shared came back, can you please provide another one?

**Comment by Sophi** [comment]
No worries at all! Thanks for the update!

**Pull request merged**
