### PR TITLE
Kerlink – HIP19 third-party manufacturer application

### PR DESCRIPTION
**Pull request by BenoitDuffez**
Rendered: https://github.com/BenoitDuffez/HIP/blob/hip19-kerlink/0019-third-party-manufacturers/kerlink.md

### CODE REVIEW

**Comment by jamiew** [comment]
Thank you, received and will review. In particular would like feedback from community on the security model

**Comment by shawaj** [comment]
Might be worth formatting in the same way as other applications as well - i.e. in a single file not a folder with sub files...

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by jamiew** [comment]
I saw that someone from Kerlink will be on community call today which is great. Can see if any questions.

**Comment by jamiew** [comment]
Per conversations in Discord and informal polling, there is wide support for approving **Kerlink** as a third-party manufacturer of Helium-compatible hotspots and I'm marking this proposal approved ✅

**Comment by shawaj** [comment]
@jamiew no big deal, but would it be worth an update to https://github.com/helium/HIP/blob/master/0019-third-party-manufacturers.md#how-to-apply to add that you are allowed to put a folder with images? Kerlink application seems nice, due to the images, and allows them to all be hosted on GH, rather than links to off-site images.

**Pull request merged**
