### PR TITLE
Multisig for chain variable updates (HIP draft)

### PR DESCRIPTION
**Pull request by evanmcc**
rendered: https://github.com/helium/HIP/blob/89075b125fc32f95bb8810686ad8062aa2dd6a59/0004-chain-var-multisig.md

### CODE REVIEW

**Comment by Vagabond** [comment]
I think it would be good to fill out the 'detailed description' section.

Additionally, should we move to multiple keys controlled by us as an interim solution that lets us work out the implementation of multiple keys before we properly distribute them?

**Comment by evanmcc** [comment]
Yeah, I don't see any problems with that, it'd be good practice.

**Comment by PharkMillups** [comment]
It sounds like @evanmcc  is still finishing this off. When he's happy with it, we'll merge it in and kick off a discussion. Keeping this PR open for now.

**Comment by jamiew** [comment]
@PharkMillups ok, sounds good. I think we'll need to renumber the file when it's submitted, HIP4 now taken

**Comment by jamiew** [comment]
@PharkMillups ok, sounds good. I think we'll need to renumber the file when it's submitted, HIP4 now taken

**Comment by jamiew** [comment]
In the interest of keeping PRs moving, I am closing this as `stale`. Please re-open if you'd like to finalize and merge it for discussion.

**Pull request closed without merging**
