### PR TITLE
Update 0000-Preventing Rug Pull, Conflicts of Interest, and Centralization

### PR DESCRIPTION
**Pull request by raynef1re**
This Helium Improvement Proposal (HIP) addresses a critical problem of potential conflicts of interest within the Helium network's governance. By proposing a ban on Nova Labs employees from submitting HIPs and participating in voting, the HIP seeks to prevent scenarios where the private interests of a corporate entity could override the collective interests of the Helium community. This is particularly important in decisions that affect network rewards distribution and technology choices, ensuring that such decisions are made impartially and in the best interest of the network's health and growth, rather than being influenced by the profit motives of a single company.

Additionally, the proposal aims to mitigate regulatory risks associated with the decentralization criteria of cryptocurrencies. By reducing the direct involvement of Nova Labs in network decision-making, the HIP addresses concerns that might arise from regulatory bodies like the SEC, which could perceive excessive corporate influence as a sign of centralization. This is crucial for maintaining the network's credibility as a decentralized system and for protecting it from potential legal and regulatory challenges that could arise from perceptions of centralization and corporate control.

HIP101 written by a Nova employee proposes changes to the network that would start a cycle of transition away from CBRS by redistributing rewards away from the community members who invested in building out the CBRS network.  As stated in the HIP, the effect would be a long term reduction in rewards to CBRS.  What it doesn’t state is that the primary effect of that HIP would be a long term increase in profits for Nova Labs by pivoting to a technology that would earn Nova Labs more at the expense of the CBRS community.  For a company to propose reducing the rewards of the CBRS community to effectively increase their own profits is essentially a rug pull.  This also disincentivizes the community from finding a fix for the CBRS issue they claimed was the reason for the HIP.  The conflict arises when Nova Labs employees can propose changes that undermine the investments of the community to the profit of their own company.

Having a Nova (formerly Helium Inc) employee proposing changes to the network also skirts the line of direct involvement for the Howey test, putting added risk on the actual decentralization of the network as it appears to be run by proxy which may garner SEC attention and lawsuits.  Nova Labs employees should be barred from voting as well for this same reason.

Ensuring Network Integrity and Decentralization: By restricting Nova Labs employees from proposing changes to the network, this proposal supports the use case of maintaining a truly decentralized network. This is crucial for the network's integrity, as it prevents any single entity from exerting undue influence or control over the network's evolution.

Protecting Community Investments: Many community members have invested significant resources in building out the CBRS network. This proposal supports the use case of safeguarding these investments by preventing proposals that could undermine the value of these community-driven efforts, ensuring that their contributions remain valuable and relevant.

Promoting Fair Governance: The proposal advocates for transparent and equitable governance within the Helium network. By making Nova Labs employees' wallets public and barring them from voting on HIPs, it supports the use case of fair and transparent decision-making processes, where conflicts of interest are minimized.

Encouraging Community-Led Solutions: This proposal also supports the use case of encouraging and empowering the community to actively participate in problem-solving. By preventing Nova Labs employees from steering the network's direction, it opens up opportunities for community members to propose and implement solutions, fostering a more collaborative and innovative environment.

Regulatory Compliance and Risk Mitigation: The proposal supports the crucial use case of maintaining regulatory compliance, particularly concerning decentralization standards that may be scrutinized by entities like the SEC. By minimizing direct involvement from Nova Labs, the proposal aims to uphold the decentralized nature of the network, thereby reducing the risk of regulatory challenges.

### CODE REVIEW

**Comment by heatedlime** [comment]
This HIP doesn't really make sense. Just because a Nova labs employee puts a HIP forward, doesn't mean it will pass. The community votes on whether that happens.  

Your HIP boils down to two things, which is actually not a problem - 

1.) Nova labs employees should not write HIPs.
Pointless to have. I'll gladly put my name on any HIP a Nova employee recommends, or write one on behalf of their ideas. So this HIP would not solve that.

2.) Nova and it's employees should not be able to vote
Nova has stated that they as a company do not and has not voted with their wallet. Nova employees may have voted in the pass, but i doubt their vote was substantial enough to sway a vote. Employees of Nova are community members too, and want the network to succeed. Baring Nova employees votes won't change much IMO. 


Further, you don't understand that no service provider wants to use CBRS, so why should we continue to reward CBRS at the same level as Wi-Fi? We have a service provider who is paying to offload data via wifi, but not CBRS (maybe $10 a day in CBRS offload vs $1700 a day in Wi-Fi offload). If you're so worried about the future of CBRS, why don't you go find a service provider who wants to join the network and use CBRS over Wi-Fi? Good luck, because the chances of winning the lottery are probably better.

**Comment by abhay** [comment]
Which one of these two PRs do you want to be considered a draft @raynef1re ?

**Comment by heatedlime** [comment]
@raynef1re if you changed the premise of the HIP to not allow Nova and its employees to vote on HIPs, that I can understand and get behind. Even though Nova as a company don't do that already, I think you could get support to formalize that in a HIP.

**Comment by raynef1re** [comment]
You can consider the second one (the updated one) as the actual one.
Sorry, I'm new to GitHub so I thoughti t would just update instead of
reposting.

So then the HIP process isn't actually about a community vote or
decentralized control, it's about a centralized pre-screening authority
that determines the course of the network by deciding which HIPs get to go
up for a vote?  I think that very premise proves the need for this HIP, as
well as raising significant legal questions as to the decentralization of
the network.

**Comment by heatedlime** [comment]
@raynef1re so currently, the only entity that decides when a HIP goes to vote is the Helium Foundation, which is a non-profit Foundation that is not associated with Nova Labs. Eventually, this will change, and this deciding factor will be given to a Helium Governance Committee, which will be made up of Community members, so still, I fail to see what you're trying to accomplish that isn't already established or in the works.

**Comment by raynef1re** [comment]
Actually, I think you make a good point.  Not-for-profit organizations are
generally expected to operate primarily for the public good, not for
private financial gain. Holding stock in a company might raise questions
about conflicts of interest, especially if the foundation's activities
could influence the value of that stock.  I think perhaps I should begin
with a HIP to prevent the Helium Foundation members from holding Helium,
Mobile, IOT, and voting as well, as it is effectively the same conflict of
interest.  I'll work on that one this week.

**Comment by heatedlime** [comment]
@raynef1re FYI, the helium foundation does not and has not voted on any HIPs. I don't think prohibiting their employees from holding MOBILE, IOT and HNT is fair and sounds preposterous. Further, the foundation has stated that they won't hold up or prevent a HIP from going to vote if that's what the community wants. Lastely, as I previously stated, this ability to determine what goes to vote is going to be given to the Helium Governance Committee made up of community members  once the committee is established. The foundation is already working on the charter to create this, as the foundation has already stated they want to be less involved in these decisions and have the community decide.

**Comment by raynef1re** [comment]
Their holding tokens while deciding which HIPs are most profitable to the
value of that token is itself a conflict of interest.  That can both lose a
company its tax exempt status and create legal ramifications that could
extend to the entire network.  I'm going to run this by the SEC in a
whistleblower complaint to see what they can find out.  I think it's for
the network's own protection that these concerns be addressed legally.  If
the network were truly decentralized, that wouldn't be possible.  And if
it's not decentralized, then these tokens are securities and due the
scrutiny of the SEC.

**Comment by heatedlime** [comment]
@raynef1re lmao ok. FWiW, I don’t believe the foundation has ever said a HIP couldn’t go to vote, so not sure how relevant any of this even is. It sounds like you’re just mad or had a bad experience with the project and are trying to take out your anger by making up a bunch of nonsense, but do as you please. It’s not worth my time anymore to try to help you understand things.

**Comment by raynef1re** [comment]
I'm not sure why you replied at all.  If centralized organizations can turn
my significant support and investments into paperweights by cutting my
rewards out of existence HIP by HIP while making a profit from my loss,
then the network is not decentralized, it is broken.  I'm doing everyone a
favor in the long run.  Stick around, there's more to come.

**Comment by hiptron** [comment]
I'm really confused by this entire thread. What is your goal here, @raynef1re?

This started as as "some entity should not vote" which (although I don't agree with) could be a reasonable proposal if well structured. It might be hard to enforce but that's the part of the discussion once proposed to the community. And now we're into a "some other entity shouldn't vote and their employees shouldn't hold tokens" conversation, which I'm certainly biased by, but I think would make it hard for said entity to operate and provide value to the network.

For the sake of not heading to the trolling lands, let's get the goals clear.

**Comment by abhay** [comment]
I'm really confused by this entire thread. What is your goal here, @raynef1re?

This started as as "some entity should not vote" which (although I don't agree with) could be a reasonable proposal if well structured. It might be hard to enforce but that's the part of the discussion once proposed to the community. And now we're into a "some other entity shouldn't vote and their employees shouldn't hold tokens" conversation, which I'm certainly biased by, but I think would make it hard for said entity to operate and provide value to the network.

For the sake of not heading to a confusing place that could be seen as trolling, let's get the goals clear.

**Comment by waveform06** [comment]
General comments from a HIP editor role:

You have not defined a method of voting so at the moment this HIP cannot be voted on.
You haven't explained why pivoting to Wifi over CBRS earns Nova more profits.
Why are Nova personal wallets banned from voting AND made public? Why do they need to be public when the foundation is requested to ensure privacy-compliant identification?
Why are you preventing Nova employees voting on HIPs unrelated to MOBILE? my HIP 100 for instance? Which related to LoRaWAN deployment in Africa

Stakeholders: You missed out on identifying important ones in the entire network. 
Nova Employees - who will have their private token transactions and related finances made public. This could cause current employees to leave the company and new ones not to apply for positions. Is this even Legal?
Helium Foundation - who will have to expend time, effort and significant costs to manage this monitoring and enforcement mechanism ... which seems to be a sort of centralized "Denylist solution" to prevent Nova even possibly having contact with HIP writers before a HIP is completed. What about any Legal challenges from false or enforcement?
And the "entire network" is not affected. LoRaWAN LNS operators are not affected by this HIP for example.


Drawbacks:
The premise seems to be that Network decentralisation is improved by centralizing control of who can write and approve HIPs when the goal of the Foundation is to decentralize control of who can write and approve HIPs as current complaints are that it centralizes too much control already. The Foundation would have to investigate intrusively every person who creates a MOBILE related HIP. No HIP should goto vote unless it can get someone to commit to write the code or perform the action, and this would involve HIP authors contacting Nova to see if they would be willing to implement the HIP. And as relationships already exist between many MOBILE HIP Proposers and Nova employees this HIP would effectively kill off any improvement to the MOBILE network by people who know how it works and are willing to spend the time creating HIPs and contacting Nova to see if they would be willing to implement it.

Would it just not be simpler to require that HIPs created that could benefit the employer of the HIP author come with a conflict of interest statement and details in the stakeholder section of how the stakeholder is benefited? And restrictions on voting on related HIPs.

**Comment by mawdegroot** [comment]
The first and foremost option to steer the Helium ecosystem is via the HIP process. If a third party user of the network, be that Nova Labs or a different entity, has a particular use case which is currently not possible within the Helium ecosystem they should be allowed to propose a change via the HIP process to enable their particular use case. By allowing a third party to propose changes that enable a particular use case the utility of the Helium ecosystem will ultimately be increased. Preventing such changes to be proposed by stake holders will therefore in my opinion be a net-negative for the Helium ecosystem.

A clear indication of affiliation, potentially together with conflict of interest statement (if applicable), would better address the issue at hand while still allowing third parties to submit improvement proposals that will ultimately lead to a better ecosystem.

It should also be noted that while anyone can propose HIPs through the HIP process, at the end of the day it is up to the entire Helium ecosystem to approve or reject the proposal through the decentralized governance system in place.

**Comment by abhay** [comment]
Closing this due to lack of engagement. Agree with the statement made by @mawdegroot

**Pull request closed without merging**
