### PR TITLE
0000-console-sunset.md

### PR DESCRIPTION
**Pull request by gristlekinginc**
Proposing sunsetting the current Helium Console as quickly as possible in order to allow businesses to build and grow the Helium LoRaWAN without having unfair competition in the market offering the service for free.

### CODE REVIEW

**Comment by waveform06** [comment]
Nik, this will need clarification on what you think is the "Helium Console"
The Foundation instance of Helium console is limited to max 10 sensors, a single organization and is "For demo and educational purposes." ,no business support. 
There is a private Nova instance of Helium console which has no limits and is for business and commercial customers and is probably outside the scope of a HIP.
Helium Console the software product is new open source and neither Helium Foundation or Nova Labs will continue feature development on it at some point before the end of 2023.
Both organizations will migrate users onto new LNSs
Helium Foundation will continue to provide a free LNS instance (Chipstack) that is limited in features and  for demo/educational use.

**Comment by gristlekinginc** [comment]
Got it.  I meant Foundation Console (not the VIP run by Nova), thank you for making that clear.

**Comment by waveform06** [comment]
@hiptron 
Gristlekinginc has confirmed this PR can be closed.

**Comment by abhay** [comment]
Closing this on behalf of the HIP Editors.

**Pull request closed without merging**
