### PR TITLE
BeiJing ManThink Tech Co. Ltd- Hip19 Manufacturer Application

### PR DESCRIPTION
**Pull request by vix-mt**
rendered view: https://github.com/helium/HIP/blob/ea6d6fd3fdb353229c41a26727b0f99f4412d00e/0019-third-party-manufacturers/manthink.md

### CODE REVIEW

**Comment by Sophi** [comment]
Hello! Thanks for your interest in joining the network. Someone from the Manufacturing Oversight Committee will be in touch. Please provide an email address for us to reach you.

**Comment by vix-mt** [comment]
> Hello! Thanks for your interest in joining the network. Someone from the Manufacturing Oversight Committee will be in touch. Please provide an email address for us to reach you.

Received with thanks.My email is vix@manthink.cn

**Comment by vix-mt** [comment]
Please cc this email zhaomingfei@manthink.cn,thanks.

> Hello! Thanks for your interest in joining the network. Someone from the Manufacturing Oversight Committee will be in touch. Please provide an email address for us to reach you.

Please cc this email:zhaomingfei@manthink.cn,thanks.

**Comment by vix-mt** [comment]
add the amout of 1st batch and modify the payment.

**Pull request merged**
