### PR TITLE
HIPxx: Split DCs Among All Transferers

### PR DESCRIPTION
**Pull request by PapaOwl**
#193 

Ed – rendered view https://github.com/PapaOwl/HIP/blob/master/0032-dc-split.md

Ed – summary:
> I propose to change the DC reward mechanism. Instead of only going to the fastest responder, the DC reward is split among all hotspots that tried to perform this duty in a timely fashion.

### CODE REVIEW

**Comment by PapaOwl** [comment]
Thank you for helping this boomer out @jamiew

**Comment by maco2035** [comment]
I think this is a good idea. It will help everyone who helps transfer a packer.
However it only will run into issues due to technical issues. Currently all the hnt is just a construct of bones. (100 million bones to 1 hnt).At the current price of a data credit, and the price of hnt, You may run into the issue where multiple hotpots can send the dc's and there won't be enough bones to split the hnt to smaller pieces that everyone can get paid, as you can't go underneath one bone to award. 
This idea is real good, so everyone who provides coverage gets paid equally on that basis as more and more of the hnt gets split rewards for the data credits spent in the area.

**Comment by jamiew** [comment]
Updated title slightly and planning to prep for merge

@PapaOwl any interest in presenting this and fielding any questions for 5-15 mins on the community call tomorrow? More info: https://dewi.org/community-call

**Comment by PapaOwl** [comment]
> 
> 
> Updated title slightly and planning to prep for merge
> 
> @PapaOwl any interest in presenting this and fielding any questions for 5-15 mins on the community call tomorrow? More info: https://dewi.org/community-call

Hello,
I am willing to present it at any time especially after I have upgraded it - this work happens now. Thinking of turning the entire HIP more graphical to visualise the issues with current protocol

**Comment by rsnodgrass** [comment]
Left my thoughts in the Discord discussion, but I think DC reward sharing is important for keeping Helium "The People's Network" for the long term.  Otherwise, those *businesses* with the $$$ to have the fastest connection to the Internet (which is commercial fiber at POPs) will reap all the DC rewards and nobody else can compete (and certainly not individuals in cities).  This won't be an issue for a few years, but it is coming as DC rewards being to rise.  Thanks for proposing this change.

**Comment by capjbadger007** [comment]
Voting to close this and archiving the related HIP discord channel. @jamiew

**Pull request merged**
