### PR TITLE
KauZ - HIP19 third party manufacturer application

### PR DESCRIPTION
**Pull request by DVdimsaf**
Rendered view: https://github.com/helium/HIP/blob/9ee6e7cd394e14e72eef0f9f422a852f14e0f6d6/0019-third-party-manufacturers/KauZ-HIP19-third-party-manufacturer

### CODE REVIEW

**Comment by Sophi** [comment]
Thanks for your proposal, someone from the Manufacturing Oversight Committee will be in touch soon.

**Comment by Sophi** [comment]
Hello, please provide a way to get in touch with you and update your HIP19 proposal with the most recent template here: https://github.com/helium/HIP/blob/master/0019-third-party-manufacturers/TEMPLATE.md
Thanks!

**Comment by Sophi** [comment]
Hello and welcome!
Please use the most recent HIP19 template here (all sections are required): https://github.com/helium/HIP/blob/master/0019-third-party-manufacturers/TEMPLATE.md
Once you've resubmitted, someone from the Manufacturing Oversight Committee will be in touch.

**Comment by BCTVFoundation1** [comment]
Hi there, I'm the board committee of Bqex.us a crypto exchange with around 4 million KYC users, I would like to be one of your Helium mining machines manufacturer, could you kindly advice and walk me with the applications steps please?

**Comment by Sophi** [comment]
HI @BCTVFoundation1 more information is here: https://github.com/dewi-alliance/hotspot-manufacturers

**Comment by DVdimsaf** [comment]
> HI @BCTVFoundation1 more information is here: https://github.com/dewi-alliance/hotspot-manufacturers

Good evening dear Sophie.
The request from BCTVFoundation1 came from the discussion thread of our company, as a manufacturer, and not from the general HIP19. Perhaps the request did not concern the organization of their own production for those who requested, but he wanted from us - KauZ LLC - to request contract manufacturing for his organization, like OEM or ODM? Forgive me for not answering right away, I just thought about it today.

**Comment by Sophi** [comment]
Could be, thanks for following up!


ᐧ

**Pull request merged**
