### PR TITLE
AirBit Miner – HIP19 3rd Party Manufacturer Application

### PR DESCRIPTION
**Pull request by airbitminer**
AirBit Miner want to join the production of Helium miner.
Our Application : https://github.com/airbitminer/HIP/blob/master/0019-third-party-manufacturers/airbit-miner.md
If you are interested in this project, please contact us :
Email: support@airbitminer.com

### CODE REVIEW

**Comment by Sophi** [comment]
Thanks for your proposal, someone from the manufacturing committee will be in touch.

**Comment by airbitminer** [comment]
Waiting for DeWi Identity~
Please contact us if any question by support@airbitminer.com

**Comment by airbitminer** [comment]
@Sophi Hello, we have send our DeWi KYC Identity to your email~

**Comment by Sophi** [comment]
@airbitminer I haven't seen it, can you retry?

**Comment by airbitminer** [comment]
@Sophi We have try, and a new email has sent, if you haven't seen it, it maybe in spam folder, thanks ^_^

**Pull request closed without merging**
