### PR TITLE
HIPxx: Anchor Gateways

### PR DESCRIPTION
**Pull request by georgica**

### CODE REVIEW

**Comment by jamiew** [comment]
Proposal looks solid to me. Will number and merge tomorrow morning 👍

**Comment by jamiew** [comment]
I assume you prefer calling it Anchor Gateways instead of Golden Gateways?

**Comment by georgica** [comment]
You can rename it to Golden Gateway since its more popular in the community

**Comment by georgica** [comment]
i corrected a few misspelled words

**Comment by cvolkernick** [comment]
also a fan of this, looks legit.

**Comment by jamiew** [comment]
Say hello to HIP22. merging

**Comment by lthiery** [comment]
@georgica I can work on specifying more clearly in the HIP, but I think that the "Golden Gateway" from a hardware specification boils down to a concentrator card that is RAK2287/RAK2247 compatible at its core. Do you agree with that?

The reason I think its important is that it may allow for eventual retrofits for operators who have any of the currently on-chain gateways.

**Comment by lthiery** [comment]
oops i'll move convo to the issue now

**Pull request merged**
