### PR TITLE
HIP Process v2 (HIP draft)

### PR DESCRIPTION
**Pull request by Senterium**
Addition of HIP 22

Ed: Rendered view: https://github.com/helium/HIP/blob/a4d3a541474e8dc5cacd98b026c445c707469dd2/0022-HIP-Process-v2

Ed: Senteriaum's notes from <https://github.com/helium/HIP/issues/81>

Seeking feedback and to build off of and add to the HIP.

HIP contains 3 major criteria:

    incentives for HIP generation and governance
    -> should rewards come from somewhere else?
    -> would it be possible to pay in hotspots? Where would those hotspots come from? Paying in hotspots incentivizes network growth.
    quality control
    -> direct democracy vs representative democracy?
    -> issue of future voter turnout and current voter turnout
    objective function
    -> should there be an objective that all HIPs are measured against?
    -> can someone be obligated to model out to ensure a HIP aligns with the objective function?
    -> should the objective function be abandoned in lou of a representative democracy?
    What is a HIP? What is the scope that can be HIP'ed.
    -> HIPs are only implemented if Helium Inc approves them. So should Helium be more explicitly defined in the HIP process?

### CODE REVIEW

**Comment by jamiew** [comment]
2nd try – thanks for the submission. Will review in detail and provide some initial feedback later today.

In meantime would you be able to reformat the document as markdown for readability? Here is an example from a previous HIP: https://raw.githubusercontent.com/helium/HIP/master/0017-hex-density-based-transmit-reward-scaling.md

**Comment by Senterium** [comment]
https://docs.google.com/document/d/1ZZxhJT4UuLTp-CmXxeoCn2sUtsff_XqAySR3junpmx8/edit?usp=drivesdk

I put it in a gdoc

**Comment by jamiew** [comment]
@Senterium could you port it to markdown? We try to keep everything in the same format so the repository is easier for everyone to understand

**Comment by jamiew** [comment]
Some other notes on this proposal I think should be addressed prior to merging for formal discussion:

* could you rewrite the summary to actually discuss the 2 major proposals the body of the HIP enumerates, one being rewarding HIP authors, the other being on-chain voting using representative democracy (right?)
* could you provide more detail on how the representative election and their HIP voting would actually work? Would these require new chain transactions? How often does this occur? How long do representatives hold their positions? How do voters vote or modify their electors vote? and so on
* the discussion about measuring "the target" in the Motivation section only stresses the importance of having a target, and does not actually specify a target. Did you have a target in mind? Otherwise I would advise removing that, as well as the other commentary that isn't directly relevant to this HIP
* lastly, I would tentatively recommend breaking this into two HIPs: one addressing the idea of HIP-author-rewards and the other would address on-chain voting. Otherwise if someone disagrees with one idea, they will vote down the whole proposal. I leave that up to you

**Review by moda83 — APPROVED** [review]

**Comment by jamiew** [comment]
@Senterium were you still planning to continue with this one? Reviewing open proposals. Thanks

**Comment by jamiew** [comment]
@Senterium I'm closing this one due to inactivity but please re-open if you're planning to address some of the requested changes. Thanks

**Pull request closed without merging**
