### PR TITLE
Launch Parameters for Solana Migration

### PR DESCRIPTION
**Pull request by bryzettler**

### CODE REVIEW

**Comment by vincenzospaghetti** [comment]
do you want to be added as an author? @bryzettler

**Comment by vincenzospaghetti** [comment]
When does this need to be implemented by? Looking for a hard date or date range.

**Comment by bryzettler** [comment]
> do you want to be added as an author? @bryzettler

Im good, I published on behalf of @ChewingGlass as we need to get the ball rolling on this one.

**Comment by bryzettler** [comment]
> When does this need to be implemented by? Looking for a hard date or date range.

Probably a week out from the go live date of 2023-03-27? @abhay @ChewingGlass

**Pull request merged**
