### PR TITLE
RAKwireless - Application for manufacturing as a third party manufacturer under HIP19

### PR DESCRIPTION
**Pull request by jmarcelino**
As per the HIP19 process this is RAKwireless's application as a third party manufacturer

Thank you very much in advance for reviewing

### CODE REVIEW

**Comment by philltran** [comment]
Rendered view at [here](https://github.com/helium/HIP/blob/a23147091130841584950c00f346f2577459d588/0019-third-party-manufacturers/RAKwireless%20-%203rd-party%20manufacturer%20application.md)
https://github.com/helium/HIP/blob/a23147091130841584950c00f346f2577459d588/0019-third-party-manufacturers/RAKwireless%20-%203rd-party%20manufacturer%20application.md

**Comment by jamiew** [comment]
Looks good. Merging to master

**Comment by jamiew** [comment]
Per conversations in Discord and informal polling, there is wide support for approving SyncroB.it/Launch Pad LLC as a third-party manufacturer of Helium-compatible hotspots and I'm marking this approval ✅ approved: https://github.com/helium/HIP#hip19-third-party-manufacturers

On behalf of the community I request that Helium Inc get in touch and arrange for ongoing key issuance.

I expect more detail will be added to HIP19 as the process for sharing keys is fleshed out.

**Comment by jamiew** [comment]
Per conversations in Discord and informal polling, there is wide support for approving **RAK Wireless** as a third-party manufacturer of Helium-compatible hotspots and I'm marking this approval ✅ approved: https://github.com/helium/HIP#hip19-third-party-manufacturers

On behalf of the community I request that Helium Inc get in touch and arrange for ongoing key issuance.

I expect more detail will be added to HIP19 as the process for sharing keys is fleshed out.

**Pull request merged**
