### PR TITLE
Moving Consensus Off Miners (HIP Draft)

### PR DESCRIPTION
**Pull request by cvolkernick**
Draft for HIP pertaining to moving consensus group off miners and creating staking / validating pools mechanism around a new validator role.

Technically includes HIP-7 readme addition I apparently haven't requested a merge for.

Ed: rendered view -> https://github.com/cvolkernick/HIP/blob/master/xxxx-move-consensus-off-miners.md

### CODE REVIEW

**Comment by cvolkernick** [comment]
my b looks like you had integrated that feedback in another form -- should be resolved now.

**Comment by jamiew** [comment]
Nice! I don't have time to fully review and merge until this afternoon ET, but I'll get back asap

**Comment by cvolkernick** [comment]
Thanks @jamiew looking forward to the discussion coming from this!

**Comment by jamiew** [comment]
Offhand I think this proposal is a great jumping off point. Obviously like to see some or all of the items in Unresolved Questions be addressed, but that would benefit from broader community discussion. Will number and merge for discussion

**Comment by jamiew** [comment]
Please direct any future discussion to #101

**Pull request merged**
