### PR TITLE
Update 0092-premine-error-correction.md

### PR DESCRIPTION
**Pull request by capjbadger007**
Removing Foundation mention.

### CODE REVIEW

**Comment by waveform06** [comment]
What is confirmed is that if the donation wallet does not meet the target then the Foundation will transfer enough to meet the target from the IOT Operations fund managed by the Foundation. 
Topping up the fund will not come direct from the Foundation. But a wallet under the control of the Foundation.

**Comment by abhay** [comment]
Is this still pending @capjbadger007 ?

**Comment by capjbadger007** [comment]
> Is this still pending @capjbadger007 ?

Oh, yes, I think so. I'm not sure how to push it forward.

**Comment by abhay** [comment]
Closing on behalf of author.

**Pull request closed without merging**
