### PR TITLE
0000-one-vote-per-hip-per-user.md

### PR DESCRIPTION
**Pull request by jeffryevans**
This HIP seeks to nullify any potential vote manipulation by allowing users only one vote per HIP. They will not be allowed to change their vote. All other voting privileges will continue as-is.

### CODE REVIEW

**Comment by waveform06** [comment]
The HIP need some evidence of your Motivation statement Jeffry and some justification why this could not just be some changing their mind.
And that is a huge drawback - you say there are none.
That no-one can change their mind and change or withdraw their vote.
Another drawback is that many large token holders may not now vote until the last minute to be sure they are voting correctly based on the latest information. This also could look like vote manipulation.

**Comment by jeffryevans** [comment]
Screenshot 2024-01-29 141444
There's little chance of people "changing their mind" here. What we have is a some 15+ billion vote swing from no to yes on this vote, during the last moments of the vote. It almost flipped the vote to passing.
I stand by my HIP.
@waveform06 - you say there's a draw back in people not being able to change their minds - I disagree. In what political election are people allowed to change their mind after they have voted? None that I know of, at least not in the US. It's a bad thing to allow people to change their minds after they have cast their vote. If there is a legitimate reason to change one's mind (e.g. something with the HIP changes during voting, which I hope would never happen), then all voting should stop and the HIP should be resubmitted for a new vote.
@waveform06 - you say there's a draw back in people waiting until the last minute to cast their vote - I disagree. When the voting time is open - we're on the block chain, which means people are able to see the vote tally in near real time, which really is not good for voting, but it's the technology we have, thus waiting until the last minute is a viable strategy to try and protect one's vote from being seen and people pivoting against it. There's no draw back there.
So, I stand by my HIP - there are no draw backs here, unless people think that minimizing potential vote manipulation is a draw back.

**Comment by waveform06** [comment]
in 3 years Ive seen so many people change their mind about HIPs during the vote period that I personally don't see anything wrong with it. Seen several "ah I didn't understand it until it was explained like that" moments, where votes got changed.
If we were running on votes only lasting one day then maybe.
But with rush to vote that so many ask for and voting periods being 7 days. There is a lot of time for better understanding of how HIPs will affect people in that time.

**Comment by jeffryevans** [comment]
I strongly disagree. But that's why we have a DAO - let's put this to a vote and let the community decide.

**Comment by waveform06** [comment]
PRs dont go immediately to vote.
They go to discussion and review by HIP editors.
So you need to add the detail in motivation in the HIP. 
And HIPs should provide information to all stakeholders. You dont have to agree with the information. But present it.
Not being able to change or withdraw a vote will be a drawback to some.

**Comment by jeffryevans** [comment]
I have included the information, and am now asking for you to please move this forward.

**Comment by heatedlime** [comment]
@jeffryevans personally, I would change it to no votes can be switched if there’s less than 24 hours left to vote. This gives voters time to change their vote if they voted early.

**Comment by heatedlime** [comment]
@jeffryevans also, you haven’t identified what token will be used to vote.

**Comment by jeffryevans** [comment]
This HIP doesn't seek to change the token used for voting. Why would I include that information?

**Comment by heatedlime** [comment]
> This HIP doesn't seek to change the token used for voting. Why would I include that information?

What token is going to be used to vote on this HIP? There’s 3 tokens…

**Comment by jeffryevans** [comment]
I have no idea what the success metrics would look like. To me, this is a straight ahead HIP, if it passes, it's a success for the ecosystem. It's meant to prevent vote manipulation, if it passes and is implemented, it would be difficult to show success data, because the potential manipulation would be prevented.

**Comment by jeffryevans** [comment]
> > This HIP doesn't seek to change the token used for voting. Why would I include that information?
> 
> What token is going to be used to vote on this HIP? There’s 3 tokens…

It should be across the board, HNT, IOT, MOBILE. If I have to choose 1, it would be MOBILE, as I'm most interested in that token.

**Comment by heatedlime** [comment]
> > > This HIP doesn't seek to change the token used for voting. Why would I include that information?
> > 
> > 
> > What token is going to be used to vote on this HIP? There’s 3 tokens…
> 
> It should be across the board, HNT, IOT, MOBILE. If I have to choose 1, it would be MOBILE, as I'm most interested in that token.

If you choose MOBILE, it’s only applicable to the MOBILE subDAO voting then. You’d have to choose veHNT to make it across all subdaos. Feel free to reach out to me on discord (heated lime) if you want any further clarification on things.

**Comment by jeffryevans** [comment]
Also, I don't believe my views should be altered at this stage, especially by gatekeepers. Once this HIP is at least put in front of the community, and several people make comments as to potential drawbacks (or anything else), then I should consider it. But right now, I have a gatekeeper pushing his personal views, views that I disagree with it. That should influence the HIP at this point.

**Comment by heatedlime** [comment]
> I have no idea what the success metrics would look like. To me, this is a straight ahead HIP, if it passes, it's a success for the ecosystem. It's meant to prevent vote manipulation, if it passes and is implemented, it would be difficult to show success data, because the potential manipulation would be prevented.

You can’t leave it blank. You have to come up with something. It could be something along the lines of  “This HIP is considered successful if voters are able to see final results that can’t be changed”

**Comment by heatedlime** [comment]
> Also, I don't believe my views should be altered at this stage, especially by gatekeepers. Once this HIP is at least put in front of the community, and several people make comments as to potential drawbacks (or anything else), then I should consider it. But right now, I have a gatekeeper pushing his personal views, views that I disagree with it. That should not influence the HIP at this point.

Thats not how the HIP process works I’m afraid. Your HIP is at best, sloppy, and the foundation is trying to help you include everything it needs to become a HIP.

**Comment by waveform06** [comment]
Feedback:
This HIP should not be one subNetwork only. It should be at least MOBILE and IOT, if not all three.
So ought to be a HIP51 addendum vote over all subNetworks.

Also as Andy has said HIPs come with code or the commitment to come with code from someone.
And Foundation devs have other preferred alternatives to implementing this.
A couple of examples are:
Truly blind voting systems
Scaling voting power so that the closer to the vote end the vote (or change) is made) the less power the vote has.

As for drawbacks you don't have to name the person who first mentioned the drawbacks (I will just be the first) You can mentione that they have been pointed out as possible drawbacks and you disagree with them.

No need to mention political voting systems, its not important - this isn't one.

"It's a bad thing to allow people to change their minds after they have cast their vote." why is that a bad thing? Its your opinion its a bad thing, or its a bad thing that is provable somehow. Which?

**Comment by abhay** [comment]
I think rather than framing this around "last minute votes" and "changing mind after a vote" it should probably be framed as a proposal towards Sybil-Resilient Online voting. It's something that's been studied a bunch outside of DAO and blockchain communities. It might be worth researching those to make this HIP more fully formed. 

For what it's worth, I'm not opposed to this coming to a discussion and numbering the HIP if we get to that structure.

Things I'd love to see are:

* How does one mitigate the risk of token positions being moved (or are they immovable) during a vote.
* The above also raises questions around KYC-ing wallets if you want to consider moves. If so who does that work and who pays for the overhead?
* Could you potentially just retract / abstain a vote in order to unlock a position in the case of wallet compromise during votes?

Being in this repo is already in front of the community. It's intentionally being considered rather than just closed. There are some reasonable arguments to be made here and I'd like to see it fleshed out.

**Comment by jeffryevans** [comment]
I've updated the language of this proposal to depersonalize it.

**Comment by jeffryevans** [comment]
> > I have no idea what the success metrics would look like. To me, this is a straight ahead HIP, if it passes, it's a success for the ecosystem. It's meant to prevent vote manipulation, if it passes and is implemented, it would be difficult to show success data, because the potential manipulation would be prevented.
> 
> You can’t leave it blank. You have to come up with something. It could be something along the lines of “This HIP is considered successful if voters are able to see final results that can’t be changed”

I have included the success metrics.

**Comment by jeffryevans** [comment]
> Feedback: This HIP should not be one subNetwork only. It should be at least MOBILE and IOT, if not all three. So ought to be a HIP51 addendum vote over all subNetworks.
> 
> Also as Andy has said HIPs come with code or the commitment to come with code from someone. And Foundation devs have other preferred alternatives to implementing this. A couple of examples are: Truly blind voting systems Scaling voting power so that the closer to the vote end the vote (or change) is made) the less power the vote has.
> 
> As for drawbacks you don't have to name the person who first mentioned the drawbacks (I will just be the first) You can mentione that they have been pointed out as possible drawbacks and you disagree with them.
> 
> No need to mention political voting systems, its not important - this isn't one.
> 
> "It's a bad thing to allow people to change their minds after they have cast their vote." why is that a bad thing? Its your opinion its a bad thing, or its a bad thing that is provable somehow. Which?

I have updated the HIP.

Also, is there a truly blind voting system being worked on now? In my view, that would solve this issue and I can just remove this HIP.

**Comment by abhay** [comment]
> Also, is there a truly blind voting system being worked on now? In my view, that would solve this issue and I can just remove this HIP.

There is a design we have around this (discussed most recently internally last week) but prioritizing it another story. Some of the dependencies around vote sealing need to be built into other protocols first, imo.

**Comment by jeffryevans** [comment]
> I think rather than framing this around "last minute votes" and "changing mind after a vote" it should probably be framed as a proposal towards Sybil-Resilient Online voting. It's something that's been studied a bunch outside of DAO and blockchain communities. It might be worth researching those to make this HIP more fully formed.
> 
> For what it's worth, I'm not opposed to this coming to a discussion and numbering the HIP if we get to that structure.
> 
> Things I'd love to see are:
> 
> * How does one mitigate the risk of token positions being moved (or are they immovable) during a vote.
> * The above also raises questions around KYC-ing wallets if you want to consider moves. If so who does that work and who pays for the overhead?
> * Could you potentially just retract / abstain a vote in order to unlock a position in the case of wallet compromise during votes?
> 
> Being in this repo is already in front of the community. It's intentionally being considered rather than just closed. There are some reasonable arguments to be made here and I'd like to see it fleshed out.

How would token positions be moved during a vote? Someone just transferring their veHNT (or whatever the corresponding coin is) to another wallet? If so, then to me, that would only strengthen the argument of this HIP, because it wouldn't matter if you sold/transferred your veHNT (for example), to someone else, as they wouldn't be able to change any vote that has already occurred.

I'm definitely not for KYC-ing wallets. My intent with this HIP is to disallow the changing of a vote after it is initially placed, nothing further. So, this is a per wallet HIP.

For retracting/abstaining votes for a compromised wallet, I'd say that this HIP protects the rightful owner of the tokens for existing votes, as they can't be changed. Beyond that, I don't see where there's much that can be done, at least not with this HIP. Do you have any ideas on this?

**Comment by waveform06** [comment]
If we had fully blind voting - and the ability to change your vote. Whats the opinion of a vote withdraw option?
Eg for votes that are not yes/no but x or y. I voted for x, but have decided after listening to arguments since the vote started that I dont agree with x or y but think z so wish to now abstain.
The current system doesnt allow this. If I voted I can only retain or change my vote - not withdraw it.

**Comment by jeffryevans** [comment]
> If we had fully blind voting - and the ability to change your vote. Whats the opinion of a vote withdraw option? Eg for votes that are not yes/no but x or y. I voted for x, but have decided after listening to arguments since the vote started that I dont agree with x or y but think z so wish to now abstain. The current system doesnt allow this. If I voted I can only retain or change my vote - not withdraw it.

I think with a truly blind voting system we can and should allow for all of this. Truly blind voting takes care of the issue this HIP seeks to fix.

**Comment by jeffryevans** [comment]
Hey folks, I greatly underestimated the time commitment needed to advance this HIP. In my mind, this HIP has a very narrow scope and is seeking to solve just one small, but important issue. But it has grown to be too much for me, and I need to focus on other things. Does someone want to take it over? If so, please let me know how you want to do it.

**Comment by waveform06** [comment]
Even if it doesn't get taken over the content of Github HIP proposals is reviewed and considered and can be added to governance process or become contributing content for other HIPs, even if they don't get past the PR stage.

**Pull request closed without merging**
