### PR TITLE
Heltec Automation - HIP19 third party manufacturer application

### PR DESCRIPTION
**Pull request by Heltec-Aaron-Lee**
As per the HIP19 process, this is the Heltec Automation application as a third-party manufacturer.

Thank you very much in advance for your review.

### CODE REVIEW

**Comment by Sophi** [comment]
Rendered view: https://github.com/helium/HIP/blob/10865771aff19db08a432a3024bc319e83813da7/0019-third-party-manufacturers/heltec.md

**Comment by Sophi** [comment]
Thanks for your submission. The manufacturing review committee will be in touch.
Can you share a contact email address?

**Comment by Heltec-Aaron-Lee** [comment]
Hi @Sophi 

We can reach by aaron@heltec.cn

**Review by Sophi — APPROVED** [review]

**Comment by Sophi** [comment]
Heltec updated text and images.

**Comment by Sophi** [comment]
Rendered view: https://github.com/HelTecAutomation/HIP/blob/fd7c8ef40a705df2f795eef0bb1e75bbf4ff18df/0019-third-party-manufacturers/heltec.md

**Comment by ke6jjj** [comment]
Thanks for the submission! And I am happy that the ROM/Flash capacity has been upgraded. 8GB would have been too small for the current, full-blockchain miner. 32GB is much better.

**Comment by ke6jjj** [comment]
I'd also like to point out that while the physical security slot is certainly a value-add that you can use, the theft of a hotspot due to its "value" is abated quite a bit because a stolen hotspot cannot be made to mine for another owner unless the original owner approves and transfers ownership to the new owner.

**Comment by Heltec-Aaron-Lee** [comment]
Hi @ke6jjj 

Our original intention is to provide an additional protective measure for the mining machine. Just like the mobile phones in our pockets, although there are security measures such as passwords, fingerprints, and facial recognition, but phones are still stolen. 😄

**Pull request merged**
