### PR TITLE
Innodev - HIP19 third party manufacturer application

### PR DESCRIPTION
**Pull request by egtogamat**
Innodev HIP19 proposal submission for third party manufacturer approval.

Email: 
terranium@innodev.ro

Link to proposal:
https://github.com/egtogamat/HIP/blob/master/0019-third-party-manufacturers/innodev.md

### CODE REVIEW

**Comment by Sophi** [comment]
Hello and welcome! 
Please use the most recent HIP19 template here: [](https://github.com/helium/HIP/blob/master/0019-third-party-manufacturers/TEMPLATE.md )
Once you've resubmitted, someone from the Manufacturing Oversight Committee will be in touch.

**Comment by adiinnodev** [comment]
Hi Sophi,

My colleague already used this template.

Thanks,

Adrian

**Comment by Sophi** [comment]
Thanks! All of the required questions were not fully answered. Could you
check please?


Sophi Kravitz
sophikravitz.com
@sophikravitz
917.806.6210

ᐧ

**Comment by adiinnodev** [comment]
Hi Sophi,

We'll double check and commit asap.

BR


Adrian

**Comment by egtogamat** [comment]
Hi Sophi,

I've update the document by inserting all the questions and adding a short answer for each of them.
Could you please take a look and let me know if it is ok?

Thank you,
Mihai

**Comment by Sophi** [comment]
Perfect thanks!

**Pull request merged**
