### PR TITLE
HIP-xxx - Pause SP Hex Boosting Rewards for Indoor Wi-Fi.md

### PR DESCRIPTION
**Pull request by mrfizzy99**
This HIP aims to pause Indoor WiFi Hex Boosting that was passed in HIP-84. 

Currently, the Helium MOBILE network has a security flaw that allows indoor wifi AP to be placed without a high degree of certainty that the AP is actually in its stated location. This HIP aims to pause Hex Boosting that was passed in HIP-84 for indoor wifi APs until a rework can be completed in a future HIP. Future provisions can include more verification mapping, more robust hardware, or reworking the economic model to remove any hex boosting arbitrages.

### CODE REVIEW

**Comment by TysonsTech** [comment]
I support this HIP. Let's Vote.

**Comment by mrfizzy99** [comment]
Would like to get this merged ASAP.  Time is essential here, and I will be pressing only the essentials and required timelines required for a HIP to go up for vote.  Little or NO discussion is needed pre-vote period, discussion of the HIP can be ongoing while the vote is active.

**Comment by abhay** [comment]
> This HIP aims to repeal and remove Hex Boosting that was passed in HIP-84.

This doesn't seem to be the actual description of the HIP. It's okay, just pointing it out.

**Comment by mrfizzy99** [comment]
> > This HIP aims to repeal and remove Hex Boosting that was passed in HIP-84.
> 
> This doesn't seem to be the actual description of the HIP. It's okay, just pointing it out.




Updated Summery.

**Comment by mrfizzy99** [comment]
This can be closed.  Proceeding with 
https://github.com/helium/HIP/pull/916

**Pull request closed without merging**
