### PR TITLE
Distributor application

### PR DESCRIPTION
**Pull request by chinsang26**
We at “ SANGHVI INDUSTRIES” request approval for distribution of Helium Hotspots in India  manufactured by Clodpi Labs India Private Limited and other manufactures from across the globe.

### CODE REVIEW

**Comment by Sophi** [comment]
HI @chinsang26, welcome! The Manufacturing Oversight Committee does not approve distributors, that is up to the vendor.

**Comment by chinsang26** [comment]
But I do see that few of the distributors like BGC-FI and Maveric digitech have been approved by you under HIP19. So if you could kindly guide me how that works it would be helpful.

**Comment by Sophi** [comment]
Sure, we're listing them on the tracker. Feel free to send sophi@dewi.org your distributor info and we'll add it to the tracker.

**Comment by chinsang26** [comment]
Hi Sophi. I have sent the email. Please do have a look and do the needful.TIA

**Pull request merged**
