### PR TITLE
SenseCAP/ Seeed - HIP19 third-party manufacturer application

### PR DESCRIPTION
**Pull request by jancee**
SenseCAP - HIP19 third-party manufacturer application

Rendered view: https://github.com/jancee/HIP/blob/pre/0019-third-party-manufacturers/seeed.md

### CODE REVIEW

**Comment by jamiew** [comment]
Thanks for your submission. The manufacturing review committee will be in touch

**Comment by jancee** [comment]
Please contact us if any question by shuyang@seeed.cc

**Comment by Scottsigel** [comment]
I've received and reviewed identity & incorporation docs for Seeed and Eric Pan (CEO). I can attest they are who they say they are.

**Comment by jancee** [comment]
Seeed SenseCAP - HIP19 Light hotspot manufacturer application

**Pull request merged**
