### PR TITLE
Hip 89

### PR DESCRIPTION
**Pull request by KeithRettig**
Made some edits based on Chris Ferebee's suggestions.

### CODE REVIEW

**Comment by abhay** [comment]
Does this conflict in any way with #718?

**Comment by ferebee** [comment]
It should be based off the content of #718, assuming that contains what Andy linked earlier in the channel.

**Comment by ferebee** [comment]
Confirm, just did a local comparison.

**Comment by KeithRettig** [comment]
Changed "funding" to "paying" (and other similar changes to try to clarify that one does not store money in the onboarding server.

**Comment by waveform06** [comment]
My thoughts on this updated version are.
(1) Stakeholders include everyone affected. So that includes MOBILE token holders (value in HNT will start to increase),  IOT Token holders (value in HNT will start to decrease) 
(2) If the HIP is urging compliance with HIP-53 then it should also require the Location Assert fee to be set to $10 or say a update to HIP 53 is required that the Mobile Network no longer has an on chain Location Assert fee, seeing as its a "Given that there is no Location Assert operation in the MOBILE subDAO" (If the latter then Maker Apps need updating)
(3) Ref "what to do with the excess funding (10 USD per Hotspot) presumed to be paid into the Onboarding Server for Location Assert is outside of the scope of this HIP." As mentioned before, there is no funding into an Onboard server and all funds are traceable in maker wallets so no presumptions about funds should be made.

**Comment by abhay** [comment]
I think this branch needs a rebase since it appears that it was based off an older branch. the filename change doesn't seem to be working correctly.

**Comment by KeithRettig** [comment]
Feel free to close this pull request as the requested action above has been completed.
Going to try to close it myself...

**Pull request closed without merging**
