### PR TITLE
Create XXX-North-Star-Mobile-Hotspot-Vendor

### PR DESCRIPTION
**Pull request by North-Star-Communications**
Add North Star as a MOBILE Hotspot Vendor

### CODE REVIEW

**Comment by Scottsigel** [comment]
@North-Star-Communications please reach out to the Foundation via email hello@helium.foundation to help facilitate onboarding as a mobile network hotspot maker. We're happy to help you through the process.

**Comment by North-Star-Communications** [comment]
We have reached out, awaiting a response. :)

**Comment by Scottsigel** [comment]
Hi @North-Star-Communications, 

At this point the only firmware available for MOBILE Hotspots is the one built by Nova Labs. I recommend speaking with that team first:

(a) Since Helium Mobile is the only active MOBILE service provider, they'll have vendor requirements separate from the Network itself.
(b) Any firmware licensing would be on their terms.

If you're planning to build your own firmware I have asked the Nova team to prepare documentation with requirements that would meet the service standards for Helium Mobile. 

Once you've resolved your plans around firmware, we can connect you with a 3rd party pentest vendor. 
Following that would be:

1. Pentest review by Foundation
2. MOBILE token lock-up per HIP-53
3. Community vote to approve vendor status

Feel free to follow-up here or DM. Thanks for your patience.

**Review by devilish66694 — APPROVED** [review]

**Comment by abhay** [comment]
Marking this for archive at the end of the week.

**Comment by abhay** [comment]
ready for archive. can be reopened if necesary.

**Pull request closed without merging**
