### PR TITLE
PR on HIP7 - Managing HIP Process

### PR DESCRIPTION
**Pull request by anthonyra**
Initial Pull Request for HIP7

### CODE REVIEW

**Comment by abhay** [comment]
@anthonyra can you change the filename back so we can see the diff between what's currently in place and this proposal?

**Comment by anthonyra** [comment]
> @anthonyra can you change the filename back so we can see the diff between what's currently in place and this proposal?

Ahhh yes, that would make sense... new to the whole "teamwork" Github commits, fetches, merges, and Pull Requests. I'll be fixing that in a jiffy.

**Comment by jamiew** [comment]
@anthonyra separating PRs from discussion is why we adopted Tracking Issues. For this one it is #26 

This branch/PR now has your HIP0014 proposal in it and I can't merge (or push to your branch to fix). Happy to ping you on Discord to help walk through how to excise, I'm @jamiedubs there

**Comment by anthonyra** [comment]
Closing this Pull Request due to re-submission

**Pull request closed without merging**
