### PR TITLE
HIP-19 REQUEST – Remove any existing vendors who have not kept to production timescales with a sufficient explanation

### PR DESCRIPTION
**Pull request by Thedailygrind**
We are beginning to encounter a problem now where big promises were made by companies who seemingly do not have the professionalism to handle large scale technology production/distribution and everything that goes with it. 

There needs to be 1) Rigid production estimates and timescales that can only be officially extended with a full explanation. 2) Consistent & regular communication. 3) The opportunity for open discussion on the challenges being faced by the community. If the official timescales are not being met without any explanation and none of the above are being done then there should be a vote as to whether their license to produce devices should be extended or removed.

### CODE REVIEW

**Comment by capjbadger007** [comment]
You have not said who will support existing hotspots if a vendor is blocked from selling units.

**Comment by cvolkernick** [comment]
> You have not said who will support existing hotspots if a vendor is blocked from selling units.

Perhaps an open standard could be adopted so the firmware needs to meet certain core requirements? It's a good point, however I don't think vendors should be able to hold customers hostage with lack of ongoing support. It does not seem like a huge ask to me to require some minimal level of frank & honest communication from vendors.

Another option could be to implement some kind of vendor-specific onboarding penalty; if an approved vendor is found (by some other authority mechanism beyond the scope of this comment) to be in violation of whatever the reporting criteria / requirements are, their onboarding fee to produce new units could be raised. They might try to pass this cost on to the customer but I would like to believe price sensitivity and competitive market forces (in combination with the degraded levels of service quality) would sort that out.

**Comment by jamiew** [comment]
Hi @Thedailygrind, is this actually a HIP edit or just a discussion topic? It's hard to tell since it appears to be forked from an older version of this repository. Would you be able to rebase to the latest `master` to help with readability?

**Comment by shawaj** [comment]
> > You have not said who will support existing hotspots if a vendor is blocked from selling units.
> 
> Perhaps an open standard could be adopted so the firmware needs to meet certain core requirements [and can be serviced / supported by other third parties]? 

The software already is essentially an open standard and for the most part can be user updated - however the process is perhaps a bit too involved for some people (and/or manufacturer hasn't documented the process). And there is little incentive for one manufacturer to take over the firmware support of another manufacturer without charge due to the costs involved. However the light gateway stuff in [gateway-rs](https://github.com/helium/gateway-rs) does improve this significantly.

We have actually already put some effort into this process [here](https://github.com/NebraLtd/helium-hardware-definitions) and already can support all Raspberry Pi based hotspots on our firmware (I have a RAK and Helium OG running it) and in the future on our dashboard too. It is relatively trivial to add new support for other hardware however the one blocker on our firmware is the need to have at least ~500mb of RAM and ~1ghz processor. This is much more powerful than most lights will be (however for reasons stated above this is less of an issue with lights). Having said that, we are already in discussions with balena to host an "openFleet" for helium users to manage their own updates using our open source repos and they seem open to the concept generally (and it would be free).

It would be great to see DeWi maintaining an open firmware update channel or something to that effect in the future, perhaps in partnership with someone like balena and using some DeWi grant funds to facilitate it. The main complexity is just ensuring hardware support for all the different processor platforms. 

Additionally, in the short term perhaps DeWi could require either fully open source software (definitely a preference as Helium is open source as is lots of crypto space and fits into the whole decentralisation thing) but if there is severe pushback to this then it could be that the vendor has to maintain a private software repo, that DeWi has secure access to, that contains all of their source code and instructions for building and deploying it so in the event there are any issues these can be easily resolved. It would also have the benefit of allowing more through security audits for example, among other things.

I don't see any reason why people wouldn't want to have the software open source anyway - given the core helium stuff already is. Would also be great to see more open source hardware in this space as well as discussed in #94

**Comment by Thedailygrind** [comment]
What do you think would be the best / easiest way for sellers to keep consistent & clear communication with its customers. What method, how often etc - What is needed to support this?

**Comment by wegelagerer** [comment]
> > > You have not said who will support existing hotspots if a vendor is blocked from selling units.
> > 
> > 
> > Perhaps an open standard could be adopted so the firmware needs to meet certain core requirements [and can be serviced / supported by other third parties]?
> 
> The software already is essentially an open standard and for the most part can be user updated - however the process is perhaps a bit too involved for some people (and/or manufacturer hasn't documented the process). And there is little incentive for one manufacturer to take over the firmware support of another manufacturer without charge due to the costs involved. However the light gateway stuff in [gateway-rs](https://github.com/helium/gateway-rs) does improve this significantly.
> 
> We have actually already put some effort into this process [here](https://github.com/NebraLtd/helium-hardware-definitions) and already can support all Raspberry Pi based hotspots on our firmware (I have a RAK and Helium OG running it) and in the future on our dashboard too. It is relatively trivial to add new support for other hardware however the one blocker on our firmware is the need to have at least ~500mb of RAM and ~1ghz processor. This is much more powerful than most lights will be (however for reasons stated above this is less of an issue with lights). Having said that, we are already in discussions with balena to host an "openFleet" for helium users to manage their own updates using our open source repos and they seem open to the concept generally (and it would be free). [Example here](https://hub.balena.io/nebraltd/helium-light-hotspot).
> 
> It would be great to see DeWi maintaining an open firmware update channel or something to that effect in the future, perhaps in partnership with someone like balena and using some DeWi grant funds to facilitate it. The main complexity is just ensuring hardware support for all the different processor platforms.
> 
> Additionally, in the short term perhaps DeWi could require either fully open source software (definitely a preference as Helium is open source as is lots of crypto space and fits into the whole decentralisation thing) but if there is severe pushback to this then it could be that the vendor has to maintain a private software repo, that DeWi has secure access to, that contains all of their source code and instructions for building and deploying it so in the event there are any issues these can be easily resolved. It would also have the benefit of allowing more thorough security audits for example, among other things.
> 
> I don't see any reason why people wouldn't want to have the software open source anyway - given the core helium stuff already is. Would also be great to see more open source hardware in this space as well as discussed in #94

Running Nebra‘s software on other devices would be a death penalty for them. I believe that the goal should be to go the other way around; running a stable software on unstable Nebra‘s.

On the other hand, removing vendors is a great idea.

**Comment by simonfuture2** [comment]
whether this is a new HIP or extension, i think this is a necessary addition to help protect our community members from being hustled and taken advantage of. This is something that i even now have finally reached my P-off level. I have stuck up and supported alot of these vendors, and now I can't help but feel like i was hustled. There are alot of vendors coming online to take advantage of our community volume, and that needs to be managed. I do not like that we have come to this point. but at the same time, it is our responsibility as a community to Call out the "Bad Actors" whether its trying to game the network or remove the HIP-19 Vendor Approval Status. Clearly, these vendors are only focused on there own bottom line, and not the Growth of the network. I feel for the people that may have ONLY had a few bucks to purchase just 1 hotspot, and now they can't participate in The Peoples Network, bc of a "Bad Actor"Vendor not sticking to there word. Or Vendors FOCUSED only on the Big Purchase orders and NOT the small 1-2 order sizes. We should start to communicate about removing Vendor Status, and also, maybe even suggest to vendors, at splitting the supply chain management, to Orders of less than 50, order sizes 50-500 and then 500+ . Maybe even Vendors could communicate to figure out that for example, Vendor A, only does supply for order sizes less than 50. Vendor B only focuses on order sizes greater than 100. and such. These are my thoughts,  pertaining to this. Would love to hear feedback from others. Either, someone Needs to stick up for the small fish in our community trying to help and participate in The Peoples Network.

**Comment by waveform06** [comment]
This one lost me at "Rigid production estimates and timescales " - Rigid Estimates are not possible

**Comment by shawaj** [comment]
> What do you think would be the best / easiest way for sellers to keep consistent & clear communication with its customers. What method, how often etc - What is needed to support this?

I don't really understand your question?

**Comment by shawaj** [comment]
> Running Nebra‘s software on other devices would be a death penalty for them. I believe that the goal should be to go the other way around; running a stable software on unstable Nebra‘s.
> 
> On the other hand, removing vendors is a great idea.

I'm very confident our software stack is superior to all other vendors. But then, I'm biased :-)

**Comment by cvolkernick** [comment]
> > What do you think would be the best / easiest way for sellers to keep consistent & clear communication with its customers. What method, how often etc - What is needed to support this?
> 
> I don't really understand your question?

I believe they're asking what your personal expectations are regarding customer service & communication, as a CEO of a HIP-19 approved manufacturer. Basically a public statement of record on your internal standards & practices regarding engagement with the customer/end user.

But @Thedailygrind should correct me if my interpretation is off.

**Comment by cvolkernick** [comment]
....or, perhaps more succinctly, I think they're asking for an acknowledgement of specific shortcomings and steps that can be taken to address them.

**Comment by Thedailygrind** [comment]
> > What do you think would be the best / easiest way for sellers to keep consistent & clear communication with its customers. What method, how often etc - What is needed to support this?
> 
> 
> 
> I don't really understand your question?

I don't think there's even a different way to ask this but @cvolkernick did a decent job.

If you don't understand such a basic question about customer service then it might be why there's an issue in the first place.

**Comment by Thedailygrind** [comment]
@jamiew @cvolkernick How do we push this forward? We are still experiencing the same issues as when this was originally suggested. The community needs to demand better business practices from all its Vendors to support the ultimate goal of Helium and at this time I see no other way how.

**Comment by cvolkernick** [comment]
@Thedailygrind See related comment: https://github.com/helium/HIP/issues/270#issuecomment-926292953

**Comment by shawaj** [comment]
> > > What do you think would be the best / easiest way for sellers to keep consistent & clear communication with its customers. What method, how often etc - What is needed to support this?
> > 
> > 
> > I don't really understand your question?
> 
> I believe they're asking what your personal expectations are regarding customer service & communication, as a CEO of a HIP-19 approved manufacturer. Basically a public statement of record on your internal standards & practices regarding engagement with the customer/end user.
> 
> But @Thedailygrind should correct me if my interpretation is off.

We have been doing weekly blogs and email updates, as well as communication on Twitter/Facebook and technical support via support tickets. As well as bug reports via GitHub.

This seems pretty robust to me, and we are actively hiring new support people almost every other week to increase our capabilities in communication and support. 

As I've said before though, we are always open to ideas if people think there is a better way we can communicate with customers.

**Comment by Thedailygrind** [comment]
> > > > What do you think would be the best / easiest way for sellers to keep consistent & clear communication with its customers. What method, how often etc - What is needed to support this?
> 
> > > 
> 
> > > 
> 
> > > I don't really understand your question?
> 
> > 
> 
> > I believe they're asking what your personal expectations are regarding customer service & communication, as a CEO of a HIP-19 approved manufacturer. Basically a public statement of record on your internal standards & practices regarding engagement with the customer/end user.
> 
> > 
> 
> > But @Thedailygrind should correct me if my interpretation is off.
> 
> 
> 
> We have been doing weekly blogs and email updates, as well as communication on Twitter/Facebook and technical support via support tickets. As well as bug reports via GitHub.
> 
> 
> 
> This seems pretty robust to me, and we are actively hiring new support people almost every other week to increase our capabilities in communication and support. 
> 
> 
> 
> As I've said before though, we are always open to ideas if people think there is a better way we can communicate with customers. 

Firstly 'weekly blog updates' is a huge stretch, and I don't think I've ever recieved an 'email' update unless a blog post has been posted. 

I think there's 3 out of your 13 blog updates that are within a week of each other. It is very clear to the community that as soon as things aren't going your way it's radio silence till it is. 

Even your latest is 10 days old,and I bet even if you posted it Sunday night you'd claim them to be 'weekly' because we all know you like using your own special definitions of terms to fit your actions. 

Secondly, as previously mentioned by others, large amounts of people are waiting on support tickets. I personally have been waiting 10 days for a support ticket response.  

My idea for better communication is investigate whoever is in charge of it because you are seemingly being lied to about their track record. Get someone who knows how to run a real business CRM program. Hiring new drones every week to answer emails off a script hasn't solved any problems as of yet.

**Comment by cvolkernick** [comment]
> Firstly 'weekly blog updates' is a huge stretch, and I don't think I've ever recieved an 'email' update unless a blog post has been posted. I think there's 3 out of your 13 blog updates that are within a week of each other. 

Have to agree with @Thedailygrind generally speaking....the "weekly" figure felt off right away at face value, just intuitively. I can understand there being no new information to report, but it would likely still be useful to communicate that there are no new updates on the same regular schedule if for nothing other than consistency & reliability.

> It is very clear to the community that as soon as things aren't going your way it's radio silence till it is.

Unfortunately whether or not this is the intention, the perception seems fairly accurate. Just to tie back to the consistency issue. People are perceptive and can pick up on narrative control, vs saying it plainly how it is regardless of how undesirable the news.

**Comment by Thedailygrind** [comment]
> We have been doing weekly blogs and email updates, as well as communication on Twitter/Facebook and technical support via support tickets. As well as bug reports via GitHub.

It is now two weeks since the last blog post. No update on amount shipped this week. Lots of expected Batch 3 devices nowhere to be seen.

& from what appears to be even more people needing support in the discord.

**Comment by cvolkernick** [comment]
> > We have been doing weekly blogs and email updates, as well as communication on Twitter/Facebook and technical support via support tickets. As well as bug reports via GitHub.
> 
> It is now two weeks since the last blog post. No update on amount shipped this week. Lots of expected Batch 3 devices nowhere to be seen.
> 
> & from what appears to be even more people needing support in the discord.

7 hours after your post...lol.

https://www.nebra.com/blogs/news/4th-october-shipping-production-update-instant-sync-and-more?goal=0_f4c509475a-f0940c075b-256734851&mc_cid=f0940c075b

**Comment by Thedailygrind** [comment]
> > > We have been doing weekly blogs and email updates, as well as communication on Twitter/Facebook and technical support via support tickets. As well as bug reports via GitHub.
> 
> > 
> 
> > It is now two weeks since the last blog post. No update on amount shipped this week. Lots of expected Batch 3 devices nowhere to be seen.
> 
> > 
> 
> > & from what appears to be even more people needing support in the discord.
> 
> 
> 
> 7 hours after your post...lol.
> 
> 
> 
> https://www.nebra.com/blogs/news/4th-october-shipping-production-update-instant-sync-and-more?goal=0_f4c509475a-f0940c075b-256734851&mc_cid=f0940c075b

It is almost funny.

**Comment by PurebredTed** [comment]
However, there hasn't been any mention specifically about outdoor units in I'm guessing over 3-4 weeks.  Some other older Blog updates did call out specifically the outdoor units, but they have seemed to disappear. :-(  It's subtle unless you ordered one and don't have it yet.

**Comment by shawaj** [comment]
> However, there hasn't been any mention specifically about outdoor units in I'm guessing over 3-4 weeks. Some other older Blog updates did call out specifically the outdoor units, but they have seemed to disappear. :-( It's subtle unless you ordered one and don't have it yet.

All of our updates encompass both indoor and outdoor 👍

**Comment by shawaj** [comment]
> Unfortunately whether or not this is the intention, the perception seems fairly accurate. Just to tie back to the consistency issue. People are perceptive and can pick up on narrative control, vs saying it plainly how it is regardless of how undesirable the news.

We have shared plenty of "undesirable" news. The fact you say otherwise implies to me that you haven't really read the updates. 

We provide regular updates, with both good and bad news in them. To say otherwise is beyond disingenuous.

**Comment by shawaj** [comment]
> Hiring new drones every week to answer emails off a script hasn't solved any problems as of yet.

Please refrain from derogatory comments about our staff. It does nothing of use and adds nothing to the conversation.

The vast majority of our support staff are Helium enthusiasts that have come from directly from the community and have a wealth of experience. Not all issues can be resolved in a day unfortunately - some have to be escalated to different teams for example. In any case we reply to all tickets and support requests and have done since the very beginning.

**Comment by cvolkernick** [comment]
> > Unfortunately whether or not this is the intention, the perception seems fairly accurate. Just to tie back to the consistency issue. People are perceptive and can pick up on narrative control, vs saying it plainly how it is regardless of how undesirable the news.
> 
> We have shared plenty of "undesirable" news. The fact you say otherwise implies to me that you haven't really read the updates.
> 
> We provide regular updates, with both good and bad news in them. To say otherwise is beyond disingenuous.

Aaron, please understand there is no disrespect involved here. You are correct that there *have* been updates, but they have not been as routine or regular as you portray.

The point here is that there is nothing wrong with being irregular; it's the arbitrary nitpicking of details that is rubbing people the wrong way. The particulars are almost irrelevant it's the nature in which responses are received.

**Comment by Thedailygrind** [comment]
> We have shared plenty of "undesirable" news. The fact you say otherwise implies to me that you haven't really read the updates. 
> 
> 
> 
> We provide regular updates, with both good and bad news in them. To say otherwise is beyond disingenuous.

So previously you said the blog posts / updates were weekly. In that case, Why wasn't something posted last week?

**Comment by Thedailygrind** [comment]
> > Hiring new drones every week to answer emails off a script hasn't solved any problems as of yet.
> 
> 
> 
> Please refrain from derogatory comments about our staff. It does nothing of use and adds nothing to the conversation.
> 
> 
> 
> The vast majority of our support staff are Helium enthusiasts that have come from directly from the community and have a wealth of experience. Not all issues can be resolved in a day unfortunately - some have to be escalated to different teams for example. In any case we reply to all tickets and support requests and have done since the very beginning. 


I was in no way speaking about any existing staff (as I clearly don't know them) but pointing out that your apparent practice of just hiring more people has done nothing to solve your problems. 

Although I'm not surprised you found something else to focus on rather than actually face the reality of the situation.

**Comment by Thedailygrind** [comment]
@jamiew Batch 3 nebra still not delivered you gonna admit they are a scam yet?

**Pull request closed without merging**
